dtolnay/cxx

gen/write.rs, macro/src/expand.rs
Implements support for our usual special cases in argument position of extern "Rust" functions. This was missed in 0.1.0 and the generated code did not compile for these cases.
```rust
extern "C" {
type T;
}
fn demo(string: String, ref_string: &String, ref_str: &str, uptr: UniquePtr<T>);
}
```
=> Implement special case types in extern Rust argument position

gen/write.rs
Fixes #13.
This way we can have:
```cpp
// c++
using Obj = void*;
```
```rust
// rust
#[cxx::bridge]
mod ffi {
extern "C" {
include!("...");
type Obj;
fn f(obj: &Obj);
}
}
```
We no longer assume anything about opaque C++ types except that something with the right name has been declared by one of the header(s).
cc @not-a-seagull
=> Support opaque types that are not structs

Cargo.toml, build.rs, src/lib.rs
Fixes #19 by using https://github.com/dtolnay/link-cplusplus to determine the C++ standard library link flag.
=> Use platform's default C++ standard library

.travis.yml, BUILD, WORKSPACE, demo-rs/BUILD, third-party/BUILD
Depends on https://github.com/bazelbuild/rules_rust/pull/295.
=> Preserve hyphens in bazel third-party crate names

README.md, demo-cxx/demo.cc, demo-cxx/demo.h, demo-rs/src/main.rs, gen/write.rs, include/cxxbridge.h, src/cxxbridge.cc, src/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h
Fixes #46.
Before: `cxxbridge::RustString`, `cxxbridge::RustStr`, `cxxbridge::RustBox`
After: `rust::String`, `rust::Str`, `rust::Box`
=> Better use of namespaces

include/cxxbridge.h, src/cxxbridge.cc
As was suggested in #8.
> Improved unnecessary code generation by using `iosfwd` instead of `iostream`. I recommend looking at what happens per translation unit when including `iostream`. It's not pretty, but `iosfwd` allows us to forward declare the `ostream` insertion operators without incurring this overhead.
=> Use iosfwd for forward declared ostream insertion operators

demo-cxx/demo.cc, gen/write.rs, include/cxxbridge.h
#8 assures that this will save headaches.
> Changed all cast operators to `explicit`. This saves more headaches in the long run, I assure you.
=> Change cast operators to explicit

syntax/check.rs, syntax/mod.rs, syntax/parse.rs
The translation to C++ isn't implemented yet, but it will parse and show a dedicated error message for now.
```rust
fn f() -> Result<()>;
^^^^^^^^^^
}
```
=> Parse Result<T> return type

gen/include.rs, gen/write.rs, macro/src/expand.rs, src/exception.rs, src/lib.rs, src/result.rs, src/rust_str.rs, syntax/check.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
This allows an `extern "C"` function to be declared with a Result\<T\> return type. We wrap the C++ function body in try/catch and turn any std::exception into a Rust error of type `cxx::Exception` using the `what()` virtual function of the C++ exception.
The reverse direction of Result⟶exception was implemented in #73.
#53
=> Implement conversion of exception⟶Result

demo-cxx/demo.cc, demo-rs/BUCK, demo-rs/BUILD, src/paths.rs, tests/BUCK, tests/BUILD, tests/ffi/tests.cc
Having `#include "path/to/lib.rs"` is cute but potentially annoying or brittle in some environments. This PR exposes `#include "path/to/lib.rs.h"` in addition.
=> Allow .rs.h extension when including generated header

gen/write.rs
Part of what's needed toward https://github.com/dtolnay/cxx/issues/53#issuecomment-599158975.
=> Factor catch implementation to static function

gen/write.rs
As proposed in https://github.com/dtolnay/cxx/issues/53#issuecomment-599158975. If the user's cxx::bridge invocation includes any header that defines the following function, they get it's behavior as the exception⟶Result conversion.
```cpp
namespace rust::behavior {
template <typename Try, typename Fail>
static void trycatch(Try &&func, Fail &&fail) noexcept try {
func();
} catch (/* up to you */) {
fail(/* const char *msg */);
}
}
```
The default behavior is equivalent to:
```cpp
} catch (const std::exception &e) {
fail(e.what());
}
```
Codebases that use Folly, for example, may be interested in behavior like this instead for better type information on the error messages:
```cpp
} catch (const std::exception &e) {
fail(folly::exceptionStr(e));
} catch (...) {
fail("<unknown exception>"); …
```
=> Allow catch behavior to be customized

syntax/check.rs, syntax/parse.rs, syntax/tokens.rs
This PR is just the parsing, so we don't do anything useful with them yet.
```console
error: function pointer support is not implemented yet
--> tests/ffi/lib.rs:35:38
|
35 |         fn c_take_callback(callback: fn(String) -> Result<usize>);
|                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> Parse function pointer types

syntax/check.rs, syntax/mod.rs, syntax/parse.rs, tests/ui/empty_struct.rs, tests/ui/empty_struct.stderr
Such structs problematically have a size of 0 in Rust and 1 in C++. Thus if they are used as a field of another struct, there would be a discrepancy in field offset for any fields after it:
```rust
mod ffi {
struct Empty {}
struct NonEmpty {
empty: Empty,
i: u8, // offset 0 in Rust, 1 in C++
}
}
```
Easiest to just disallow for now with an error message.
```console
error: structs without any fields are not supported
--> $DIR/empty_struct.rs:3:5
|
3 |     struct Empty {}
|     ^^^^^^^^^^^^^^^
```
=> Disallow shared structs having 0 fields

macro/src/expand.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
Minimal fix to get it working.
I put in a test with a C++ function that returns `Result<UniquePtr<CxxString>>`.
=> Make Result work with UniquePtr, RustBox, RustString, Str

gen/write.rs, include/cxx.h, macro/src/expand.rs, src/function.rs, src/lib.rs, syntax/check.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
For example:
```rust
mod ffi {
extern "C" {
fn c_take_callback(callback: fn(String) -> usize);
}
}
```
This corresponds to an argument of type `rust::Fn<`​`>` on the C++ side, with an `operator()` to call the Rust function pointer.
```cpp
void c_take_callback(rust::Fn<size_t(rust::String)> callback) {
callback("...");
}
```
---
The generated code is currently as follows; we can make this better in subsequent PRs.
```cpp
void cxxbridge02$c_take_callback(::rust::Fn<size_t(::rust::String)> callback) noexcept {
void (*c_take_callback$)(::rust::Fn<size_t(::rust::String)>) = c_take_callback;
c_take_callback$(callback);
}
size_t cxxbridge02$c_take_callback$callback$1(::rust::String *_0, void *) noexcept;
size_t cxxbridge02$c_take_callback$callback$0(::rust::String _0, void *extern$) noexcept { …
```
=> Implement function pointer passing from Rust to C++

include/cxx.h
Some people prefer to write indirect calls as `(*f)(args...)` rather than plain `f(args...)`.
=> Allow calling fn pointers with explicit indirect call syntax

gen/write.rs, macro/src/expand.rs, src/unique_ptr.rs
=> Do not emit UniquePtr::new for opaque C types

src/unique_ptr.rs, tests/unique_ptr.rs
The impls will panic on a null pointer. Panicking in Deref is unconventional but this matches the reality of how unique_ptr is used in practice in C++. In most places that unique_ptr is passed around they can never be null, and in the few cases where null is allowed the programmer is responsible for keeping track and handling those pointers carefully.
Providing these impls is less bad than users writing `ptr.as_ref().unwrap()` everywhere, because at least this way we can get the panic message to include type info to help debugging.
=> Deref and DerefMut for UniquePtr

gen/include.rs, gen/write.rs, include/cxx.h
Hybrid of https://github.com/dtolnay/cxx/commit/15b5b10763219ba6386abae073a11dd6b06a8ea1 and https://github.com/dtolnay/cxx/commit/ef1bf1822c243a38832602b75d21d3da1fd77804 and https://github.com/dtolnay/cxx/pull/96#issuecomment-612150188.
cc @myronahn @AlesTsurko
closes #96
=> Define rust::isize with Windows support

src/cxx.cc
Partially addresses #92 (it remains to figure out how to nicely expose constructing a rust::String from a std::string when exceptions are off).
=> Accept RUST_CXX_NO_EXCEPTIONS to disable throwing

include/cxx.h
Closes #102.
The use of list initialization is because the only types that can be boxed *and* constructed by C++ are shared structs, and we take care that those are always aggregates. (Opaque Rust types aren't constructible by C++, and opaque C++ types aren't allowed to be placed in Box.)
=> Add in_place constructor for Box

src/cxx.cc
=> Use terminate instead of abort in no-exceptions mode

cmd/src/main.rs
For those building without Cargo, it may be a little awkward to specify
the `CARGO_PKG_AUTHORS` environment variable (in some cases perhaps
requiring a wrapper script around rustc).
=> Specify author explicitly.

README.md, gen/write.rs, include/cxx.h, macro/src/expand.rs, src/lib.rs, src/rust_sliceu8.rs, syntax/check.rs, syntax/impls.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs, syntax/types.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
This change adds specifically, support for `&[u8]` with a corresponding
`rust::Slice<uint8_t>` type. No other types of slice are permitted. The
rationale is that it may be common to pass binary data back and forth
across the FFI boundary, so it's more urgent to get this in place sooner.
Broader support for other slices can wait for the future.
But, both C++ and Rust-side bindings should allow the existing support
to be broadened to other Slice types in future without code changes.
A few specific notes:
* The name `rust::Slice` might be better as `rust::SliceRef` but I'm
following the precedent of `rust::Str`.
* It would be good to add constructors from `std::span` but as that's
a C++20 feature, that may have to wait until C++ feature detection
is resolved. Meanwhile, …
=> Adding &[u8] support.

Cargo.toml, README.md, demo-cxx/demo.cc, demo-cxx/demo.h, demo-rs/src/main.rs, gen/write.rs, macro/src/expand.rs, src/lib.rs, syntax/check.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
This adds support for calling C++ and Rust methods with the syntax suggested in #51:
fn get_name(self: &ThingC) -> &CxxString;
fn print(self: &ThingR);
It requires Rust 1.43 to use this syntax.
=> Support calling C++ and Rust methods

gen/write.rs, macro/src/expand.rs, syntax/mangle.rs, syntax/mod.rs
I'd like to centralize the mangling scheme (anything dealing with symbols containing `$`) in one place to make it easier to identify potential collisions and mitigate them. For example we need to be sure that the symbols we take up for built in types like std::string can't collide with some symbol derived from some user-defined type. More PRs will follow to fix the remaining places that are using `format!` to paste together ad hoc symbols.
=> Share function link name mangling logic

WORKSPACE
This picks up https://github.com/bazelbuild/rules_rust/pull/308.
=> Bump bazel rules_rust to pull in optional extra_target_triples

syntax/check.rs, syntax/impls.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs, tests/ui/disallow_lifetime.rs, tests/ui/disallow_lifetime.stderr
Previously these were being silently accepted and ignored.
```console
error: references with explicit lifetimes are not supported
--> $DIR/disallow_lifetime.rs:9:22
|
9 |         fn f(string: &'a String);
|                      ^^^^^^^^^^
error: references with explicit lifetimes are not supported
--> $DIR/disallow_lifetime.rs:5:14
|
5 |         fn f(&'static self);
|              ^^^^^^^^^^^^^
```
=> Trigger error on explicitly specified lifetimes in a reference type

syntax/check.rs, tests/ui/unrecognized_receiver.rs, tests/ui/unrecognized_receiver.stderr
```rust
mod ffi {
extern "C" {
fn f(self: &Unrecognized);
}
}
```
```console
error: unrecognized receiver type
--> $DIR/unrecognized_receiver.rs:4:20
|
4 |         fn f(self: &Unrecognized);
|                    ^^^^^^^^^^^^^
```
Previously this was accepted by the code generator and only produced errors later during C++ and Rust compilation.
```console
tests/ffi/lib.rs.cc:522:49: error: ‘Unrecognized’ does not name a type
522 | void cxxbridge02$Unrecognized$f(const Unrecognized &self) noexcept {
|                                       ^~~~~~~~~~~~
```
=> Trigger error on unrecognized ident in receiver's type

syntax/check.rs, syntax/parse.rs, tests/ui/reserved_name.rs, tests/ui/reserved_name.stderr
This avoids aborting the parser so that we are able to produce more than one error from the same compilation.
=> Defer error on restricted type names

syntax/check.rs, syntax/parse.rs, tests/ui/unnamed_receiver.rs, tests/ui/unnamed_receiver.stderr
This implementation avoids aborting the parser so that we can emit more than one error at a time, and also works well for `self: &Self` syntax.
=> Defer computing the Self type of methods

syntax/parse.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
This adds support for wildcard variable names by internally giving them unique names.
Fixes #154.
This seems simpler than trying to ensure we catch all uses of an ident named "_" and naming them appropriately.
=> Allow wildcard argument names.

include/cxx.h, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
https://en.cppreference.com/w/cpp/iterator/iterator_traits
`std::iterator_traits` requires the following 5 types:
- `difference_type` - a signed integer type that can be used to identify distance between iterators
- `value_type` - the type of the values that can be obtained by dereferencing the iterator. This type is void for output iterators.
- `pointer` - defines a pointer to the type iterated over (value_type)
- `reference` - defines a reference to the type iterated over (value_type)
- `iterator_category` - the category of the iterator. Must be one of iterator category tags.
The current `const_iterator` for `rust::Vec<T>` only defined `value_type` and `reference` which caused an error when using `std::copy` on gcc 7.5.0 on Ubuntu but seemed to work fine on MacOS.
=> Add all std::iterator_traits required types to const_iterator of rust::Vec<T>

gen/src/write.rs, macro/src/expand.rs, syntax/check.rs, syntax/ident.rs, syntax/mod.rs, syntax/parse.rs, syntax/types.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs, tests/ui/data_enums.rs, tests/ui/data_enums.stderr, tests/ui/duplicate_enum_discriminants.rs, tests/ui/duplicate_enum_discriminants.stderr, tests/ui/empty_enum.rs, tests/ui/empty_enum.stderr, tests/ui/enum_match_without_wildcard.rs, tests/ui/enum_match_without_wildcard.stderr, tests/ui/generic_enum.rs, tests/ui/generic_enum.stderr, tests/ui/non_integer_discriminant_enum.rs, tests/ui/non_integer_discriminant_enum.stderr
This adds support for passing C-style enums between Rust and C++.
We use the Rust representation for enums suggested by dtolnay in #132.
Note that as this does not use real enums, Rust code cannot treat them
as normal enums, e.g., by converting them to integers.  But common
uses such as pattern matching remain unchanged.
=> Support C-style enums

macro/src/expand.rs, syntax/check.rs, tests/ui/enum_overflows.rs, tests/ui/enum_overflows.stderr
This both checks for enum values that are illegal due to overflow and
ensures we do not overflow on valid enums.
Fixes #176.
=> Properly handle enum discriminant overflows.

macro/src/expand.rs, tests/test.rs, tests/ui/enum_match_without_wildcard.stderr
=> Expose the enum value to Rust as a field

gen/build/Cargo.toml, gen/cmd/Cargo.toml, gen/src/mod.rs, third-party/BUCK, third-party/BUILD, third-party/Cargo.lock
Closes #130. This pulls in https://github.com/alexcrichton/proc-macro2/pull/220.
Tested by adding this:
```toml
[profile.dev]
panic = "abort"
```
to the bottom of Cargo.toml and running `cargo run --manifest-path /git/cxx/gen/cmd/Cargo.toml -- /git/cxx/tests/ffi/lib.rs`, which aborts before this PR and succeeds after this PR.
=> Support building C++ code generator with panic=abort

gen/src/mod.rs, macro/src/expand.rs, syntax/check.rs, syntax/mod.rs, syntax/parse.rs, syntax/report.rs, syntax/types.rs, tests/ui/multiple_parse_error.rs, tests/ui/multiple_parse_error.stderr
Fixes #183.
Before:
```console
error: struct with generic parameters is not supported yet
--> $DIR/multiple_parse_error.rs:3:5
|
3 |     struct Monad<T>;
|     ^^^^^^^^^^^^^^^
```
After:
```console
error: struct with generic parameters is not supported yet
--> $DIR/multiple_parse_error.rs:3:5
|
3 |     struct Monad<T>;
|     ^^^^^^^^^^^^^^^
error: unrecognized ABI
--> $DIR/multiple_parse_error.rs:5:5
|
5 |     extern "Haskell" {
|     ^^^^^^^^^^^^^^^^
```
=> Batch parse errors

gen/src/write.rs, macro/src/expand.rs, syntax/types.rs, tests/ffi/lib.rs, tests/ffi/tests.h
This allows listing an enum in an extern "C" block as well as in the shared block.  In this case, we do not emit the C++ declaration of the enum but instead emit static assertions that it has the values that we expect.
Do you know a good way to test the assertions?  The ui tests don't seem to compile the generated C++ files, so I'm not sure how to do it.
I'm also considering refactoring the discriminant generation code somewhere now that it's mostly duplicated in three different places.
Closes #177.
=> Support enums defined in C++ code.

gen/src/write.rs, macro/src/expand.rs, syntax/check.rs, syntax/mod.rs, syntax/parse.rs, tests/ui/duplicate_enum_discriminants.stderr, tests/ui/enum_overflows.stderr
This allows us to reuse the computation in multiple places later.
=> Compute enum discriminant during parsing

build.rs, demo-rs/build.rs, gen/build/src/lib.rs
This means that clang++ will be called instead of clang.
This was causing me issueing when trying to use the nix version of clang, not sure why.
=> Add cpp flag to cc

README.md, build.rs, demo-rs/build.rs, gen/build/src/lib.rs, src/lib.rs, tests/ffi/build.rs
To avoid a compiler warning on MSVC, use `flag_if_supported` rather than `flag` for setting `-std=c++11`
Fixes #44
=> avoid MSVC warning via flag_if_supported

gen/src/write.rs, macro/src/expand.rs, syntax/atom.rs, syntax/attrs.rs, syntax/discriminant.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/ui/enum_inconsistent.rs, tests/ui/enum_inconsistent.stderr, tests/ui/enum_match_without_wildcard.stderr, tests/ui/enum_out_of_bounds.rs, tests/ui/enum_out_of_bounds.stderr, tests/ui/enum_overflows.rs, tests/ui/enum_overflows.stderr, tests/ui/enum_unsatisfiable.rs, tests/ui/enum_unsatisfiable.stderr
Fixes #175.
In order, the choice of repr is based on:
- **#\[repr(...)\] attribute**
```rust
#[repr(u16)]
enum E {  //:u16
A,
B,
}
```
- otherwise, **integer suffix**
```rust
enum E {  //:isize
A = 0isize,
B,
}
```
- otherwise, **range of discriminant values**
The first of `u8`, `i8`, `u16`, `i16`, `u32`, `i32`, `u64`, `i64` that can fit all of the values.
```rust
enum E {  //:i16
A = -1,
B = 2020,
}
```
FYI @jgalenson
=> Choose enum discriminant type based on repr attributes, suffixes, values

.github/workflows/ci.yml
Fixes #199. I guess the default ordering of $PATH was changed.
=> Fix permission denied failure in bazel CI job

gen/src/include.rs, gen/src/write.rs, syntax/mod.rs, syntax/parse.rs, tests/ui/include.rs, tests/ui/include.stderr
For example:
```rust
#[cxx::bridge]
mod ffi {
extern "C" {
include!("path/to/quoted");
include!(<path/to/bracketed>);
...
}
}
```
Emitted as:
```cpp
#include "path/to/quoted"
#include <path/to/bracketed>
```
=> Parse include!(<path/to/bracketed>)

Cargo.toml, build.rs
As described in https://github.com/dtolnay/cxx/pull/80#issuecomment-605794135. Currently unused, but will be needed when integrating std::optional or std::string_view support.
```toml
[dependencies]
cxx = { version = "0.3", features = ["c++17"] }
```
=> Add cargo cfgs for opt in to newer standards

tests/test.rs
On some targets (e.g. armv7-unknown-linux-gnueabihf) `std::os::raw::c_char` is defined as `u8` instead of `i8`.   This change fixes the compile error that results.
The docs (https://doc.rust-lang.org/std/os/raw/type.c_char.html) say that `std::os::raw::c_char` will always be either `u8` or `i8`.
=> Fix for when std::os::raw::c_char is u8 (armv7)

gen/src/write.rs, src/exception.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
A FFI C++ member function (i.e. function w/receiver) with no args and an indirect return (i.e. one that returns a `Result<T>`) was generating a function signature with a missing comma between the self arg and the indirect return parameter.
The `get_fail()` test member function will trigger this error.
The one-liner fix is in `gen/src/write.rs`
=> Fix issue with indirect return for C++ member function w/no args

gen/cmd/src/main.rs, gen/src/mod.rs, gen/src/write.rs
This option to the 'cxxbridge' command line tool allows
users to specify (for example)
```__attribute__((visibility("default")))```
or
```__declspec(dllexport)```
on C functions which may be exported from a shared object
as they may be required by Rust code in different binaries.
Fixes #219.
=> Allow DSO export for C Rust bindings.

BUILD, WORKSPACE, third-party/BUILD
Proc macro dependencies are now required to be declared separately from ordinary `deps`.
This is the failure otherwise:
```console
ERROR: /git/cxx/third-party/BUILD:65:1: in rust_library rule //third-party:proc-macro-error: 
Traceback (most recent call last):
File "/git/cxx/third-party/BUILD", line 65
rust_library(name = 'proc-macro-error')
File "/home/.cache/bazel/ebce1d0721fb68dda9c70c0dd1405803/external/io_bazel_rules_rust/rust/private/rust.bzl", line 115, in _rust_library_impl
rustc_compile_action(ctx = ctx, toolchain = toolchain, cr...), ...)
File "/home/.cache/bazel/ebce1d0721fb68dda9c70c0dd1405803/external/io_bazel_rules_rust/rust/private/rustc.bzl", line 444, in rustc_compile_action
collect_deps(ctx.label, crate_info.deps, crate_in..., <2 more arguments>)
File …
```
=> Update bazel Rust rules repo

BUCK, BUILD, gen/cmd/Cargo.toml, gen/cmd/src/app.rs, gen/cmd/src/main.rs, third-party/BUCK, third-party/BUILD, third-party/Cargo.lock
This eliminates several dependencies (heck, proc-macro-error, proc-macro-error-attr, structopt, structopt-derive, syn-mid, unicode-segmentation) and makes it somewhat more natural to exercise more control over the help output.
<br>
```console
cxxbridge 0.3.4
David Tolnay <dtolnay@gmail.com>
https://github.com/dtolnay/cxx
USAGE:
cxxbridge <input>.rs              Emit .cc file for bridge to stdout
cxxbridge <input>.rs --header     Emit .h file for bridge to stdout
cxxbridge --header                Emit rust/cxx.h header to stdout
FLAGS:
-h, --help       Print help information
--header     Emit header with declarations only
-V, --version    Print version information
OPTIONS:
--cxx-impl-annotations <cxx-impl-annotations>
Optional annotation for implementations of C++ function wrappers that …
```
=> Switch cli arg parsing from structopt to clap

gen/src/write.rs
This avoids problems with duplicate definitions when the
generated .cc ends up including the generated .h via intermediate
includes.
I may yet add another commit here to add some test code.
Fixes #230.
=> Writing include guards around each type.

include/cxx.h, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
Adds operator[], at(), front(), and back() to rust::Vec.
This is the read-only accessor side of #149, not sure if we want mutable accessors.
=> Add rust::Vec accessors

Cargo.toml, build.rs, flags/Cargo.toml, flags/src/impl.rs, flags/src/lib.rs, tests/ffi/Cargo.toml, tests/ffi/build.rs, third-party/Cargo.lock
This PR introduces a way to share C++ compiler flags (`-std=c++14` etc) between the `cxx` crate and our test suite, including MSVC support. This bypasses the Cargo dependency resolution bug (https://github.com/rust-lang/cargo/issues/6915) which was blocking the previous attempt in #205.
Closes #205.
FYI @philipcraig
=> Specify consistent c++ standard between cxx and cxx-test-suite

gen/build/src/error.rs, gen/build/src/lib.rs, gen/build/src/paths.rs, gen/src/error.rs, gen/src/fs.rs, gen/src/mod.rs
Before:
```console
cxxbridge: No such file or directory (os error 2)
```
After:
```console
cxxbridge: Failed to read file `path/to/nonexistent`
Caused by:
No such file or directory (os error 2)
```
=> Add context to i/o errors

BUCK, BUILD, build.rs, src/lib.rs, third-party/BUCK, third-party/BUILD
The only purpose of that crate is its Cargo build.rs, which emits rustc-link-lib flags to Cargo.
=> Remove link-cplusplus dependency from non-Cargo builds

demo/Cargo.toml, gen/build/src/cargo.rs, gen/build/src/error.rs, gen/build/src/lib.rs, gen/build/src/paths.rs, gen/src/fs.rs, tests/BUCK, tests/BUILD, tests/ffi/lib.rs, tests/ffi/module.rs, tests/ffi/tests.cc, third-party/Cargo.lock
Fixes #213. Fixes #88. Supersedes #214. Supersedes #253.
The major improvement is that we no longer care where Cargo's target dir is located. Instead of doing anything based on relative paths from the target dir, we do it only based on the paths the user passes to cxx_build::bridge, which we know are relative to the manifest dir because that's the current directory when a build script runs.
For an invocation like `cxx_build::bridge("src/lib.rs")` the resulting layout of the OUT_DIR would be:
```console
$  exa -T target/debug/build/cxx-demo-1848f7a3fc5320f1/out/
target/debug/build/cxx-demo-1848f7a3fc5320f1/out
└── cxxbridge
├── cxx-demo
│  └── src
│     ├── lib.rs -> ./lib.rs.h
│     ├── lib.rs.cc
│     └── lib.rs.h
└── rust
└── cxx.h
```
and the include paths would be `#include …
=> Rewrite cxx-build crate

gen/src/fs.rs, gen/src/mod.rs
Closes #278.
Tested with:
```console
$ echo '#[cxx::bridge] mod ffi { struct S { x: u8 } }' | target/debug/cxxbridge -
```
=> Accept `-` to mean stdin in command line code generator

gen/build/Cargo.toml, gen/build/build.rs, gen/cmd/Cargo.toml, gen/cmd/build.rs, gen/lib/Cargo.toml, gen/lib/build.rs, macro/Cargo.toml, macro/build.rs
Only needed for local development (not for building `cxx` as a dependency from crates.io).
=> Detect when symlink not enabled

gen/cmd/src/app.rs, gen/cmd/src/main.rs, gen/cmd/src/test.rs
`cxxbridge ... -o generated.cc` is equivalent to `cxxbridge ... > generated.cc` but can be more convenient to some build systems, e.g. would have avoided needing a new `run_binary_capture_stdout.sh` in https://fuchsia.googlesource.com/fuchsia/+/f43c8da66eba6353f0b8c8a3673bb31a34751b7f%5E%21/ or a new `redirect_stdout` functionality in https://fuchsia.googlesource.com/fuchsia/+/c33dc953dff0445edede5ab135b8aeb12235f6a2%5E%21/.
=> Add -o flag to set output file for cli

src/cxx_string.rs, src/cxx_vector.rs, src/exception.rs, src/lib.rs, src/opaque.rs, src/result.rs, src/rust_sliceu8.rs, src/rust_str.rs, src/rust_string.rs, src/rust_vec.rs, src/symbols/exception.rs, src/symbols/rust_str.rs, src/symbols/rust_string.rs, src/symbols/rust_vec.rs, src/unique_ptr.rs
This makes it easier to see where libstd is really being needed, and evaluate possible no-std support.
Answer: currently used almost nowhere. We use liballoc in a couple places related to error handling, and for https://docs.rs/cxx/0.4.4/cxx/struct.CxxString.html#method.to_string_lossy which can easily be put behind a feature cfg. And we use libstd currently *only* for catching and aborting on unwind across the FFI. Seeing as `cfg(panic = "abort")` is getting ready to land (https://github.com/rust-lang/rust/pull/74754), it will likely be quite easy to support no-std in `panic = "abort"` mode at least, which is potentially relevant to Fuchsia. For `panic = "unwind"` mode we'll have to think about how else to rule out the UB from unwinding a Rust panic into C++ code.
=> Import from libcore/liballoc where possible

gen/src/write.rs
The `indirect_return` functions checks if a function signature either throws or needs indirect ABI and decides if `::rust::MaybeUninit` should be added to the generated C++ code. However the declaration for the `::rust::MaybeUninit` was only generated if the function needed indirect ABI so I ended up with functions that returned a Result generated code that used `::rust::MaybeUninit` but didn't have the declaration. This PR should make sure that the `::rust::MaybeUninit` declaration is part of the generated code if a function returns a Result.
=> Make sure MaybeUninit is part of generated code for Rust functions returning Result

gen/lib/Cargo.toml
We need to stay roughly correlated such that cargo users do not
get mismatches between `cxxbridge04$` (generated by the main cxx
crate) and `cxxbridge03$` (which is what they get when they fetch
cxx-gen 0.1 from cargo).
In other words, even if the goal is to rev this library on a
different cadence, that cadence needs to be at least as fast
as breaking changes in `cxx` itself.
=> Bump gen/lib version to match cxx.

demo/BUCK, demo/BUILD, tests/BUCK, tests/BUILD
This will be more amenable to factoring out to a macro.
=> Use more systematic naming for generated code targets

gen/cmd/src/app.rs, gen/cmd/src/main.rs, gen/cmd/src/test.rs, gen/src/mod.rs
Closes #64.
```console
$ cxxbridge src/lib.rs -o lib.rs.h -o lib.rs.cc
```
Based on #318 we'll detect the one ending in `.h` as the header.
=> Handle multiple outputs from the same cxxbridge invocation

tools/bazel/rust_cxx_bridge.bzl
As proposed in https://github.com/dtolnay/cxx/pull/307#issuecomment-699225624. `run_binary` does not involve Bash, unlike `genrule`.
=> Switch Bazel rules from genrule to run_binary

tools/bazel/rust_cxx_bridge.bzl
This is preferable because if the input contains an error, we don't want to see a duplicate diagnostic printed by each separate genrule.
=> Combine bazel codegen steps into one run of cxxbridge

tools/buck/rust_cxx_bridge.bzl
This is preferable because if the input contains an error, we don't want to see a duplicate diagnostic printed by each separate genrule.
=> Combine buck codegen steps into one run of cxxbridge

macro/src/expand.rs, syntax/mod.rs, syntax/parse.rs
=> Preserve docs on aliases

gen/src/write.rs, macro/src/expand.rs, src/extern_type.rs, src/lib.rs, syntax/check.rs, syntax/types.rs, tests/ui/by_value_not_supported.stderr
Fixes #313.
This is a breaking change as it requires all implementers of `ExternType` to add another associated type. Defaults for associated types are an unstable feature, the compiler tells me. Perhaps we should avoid this by using a new trait, `ExternTypeKind`, instead.
=> Allow type aliases to be marked as Trivial.

macro/src/expand.rs, src/extern_type.rs, src/lib.rs
=> Update documentation and API of Trivial and Opaque kind markers

gen/src/write.rs, macro/src/expand.rs, syntax/check.rs, syntax/types.rs, tests/ui/by_value_not_supported.stderr
The previous error of `"error: passing non-trivial C++ type by value is not supported"` was not sufficient to put someone on the right track of how to make their C++ type "trivial". The new error points to your `type` and very briefly explains what is needed and why, referring to cxx::ExternType where the documentation covers this use case in detail.
```console
error: using opaque C++ type by value is not supported
--> $DIR/by_value_not_supported.rs:3:16
|
3 |     struct S { c: C }
|                ^^^^
error: needs a cxx::ExternType impl in order to be used as a field of `S`
--> $DIR/by_value_not_supported.rs:10:9
|
10 |         type C;
|         ^^^^^^
```
Follow-up to #325.
=> Add dedicated error message referring to cxx::ExternType when opaque type is used by value

gen/src/write.rs, macro/src/expand.rs, syntax/check.rs, syntax/file.rs, syntax/ident.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs, syntax/types.rs, tests/ui/bad_explicit_impl.rs, tests/ui/bad_explicit_impl.stderr, tests/ui/impl_trait_for_type.rs, tests/ui/impl_trait_for_type.stderr, tests/ui/nonempty_impl_block.rs, tests/ui/nonempty_impl_block.stderr, tests/ui/unique_ptr_twice.rs, tests/ui/unique_ptr_twice.stderr
As discussed in #312 and elsewhere. Supersedes #329. We use the following `impl` syntax to indicate that we'd like the expansion of the ffi mod to include a given instantiation of UniquePtr, even if otherwise not mentioned in any of the extern function signatures:
```rust
#[cxx::bridge]
mod ffi {
extern "C" {
type C;
}
impl UniquePtr<C> {}
}
```
The same also works if the UniquePtr were to be an extern type alias (`type C = path::to::C;`). In that case it's up to the user whether to place the UniquePtr impl in one ffi module or the other, subject to the Rust orphan rule.
Closes #236. Closes #312. Closes #329.
=> Explicitly requesting an instantiation

macro/src/expand.rs, syntax/impls.rs, syntax/set.rs, syntax/types.rs, tests/ui/unique_ptr_twice.stderr
Before:
```console
error[E0119]: conflicting implementations of trait `cxx::private::UniquePtrTarget` for type `here::C`:
--> $DIR/unique_ptr_twice.rs:10:1
|
1  | #[cxx::bridge]
| -------------- first implementation here
...
10 | #[cxx::bridge]
| ^^^^^^^^^^^^^^ conflicting implementation for `here::C`
|
= note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
After:
```console
error[E0119]: conflicting implementations of trait `cxx::private::UniquePtrTarget` for type `here::C`:
--> $DIR/unique_ptr_twice.rs:16:5
|
7  |     impl UniquePtr<C> {}
|     ----------------- first implementation here
...
16 |     impl UniquePtr<C> {}
|     ^^^^^^^^^^^^^^^^^ conflicting implementation for `here::C`
```
Cleanup of #336.
=> Improve error message on a conflicting explicit impl

src/extern_type.rs
It isn't actually a requirement that the type have no destructor as brought up by the previous paragraph. Rather, it just needs to be safe for values of that type to be moved via Rust's memcpy-based move semantics.
The distinction is relevant e.g. for `struct S { s: String }` which would have a C++ destructor and nontrivial implicitly defined move constructor but still be safely memcpy movable. C++ has no analogue of "trivially destructive-movable" which is the semantic we are really interested in.
=> Tweak wording of the triviality requirement

macro/src/expand.rs
This isn't directly usable now, but will be needed for #297. Doing this now since this is a breaking change (previously the caller could have written their own ExternType impl for these types, not that they would have had a reason to) and we currently have another breaking change pending anyway (#325).
=> Emit an ExternType impl for shared structs and enums

BUCK, BUILD, build.rs, gen/build/src/error.rs, gen/build/src/lib.rs, gen/build/src/paths.rs
This is the second near complete rewrite of cxx-build (following #276) but I am feeling good about this one.
<br>
References:
- https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key
- https://doc.rust-lang.org/cargo/reference/build-script-examples.html#using-another-sys-crate
Cargo has some functionality for build scripts where they can emit metadata as key-value pairs to be made available as environment variables to the build scripts of **directly dependent** crates. This is exactly the limitation that we want to impose. By building on this, we're able to require that your crate declare a direct dependency on the other crate in order to be able to #include their headers in your C++ build. Headers from transitive dependencies are not made available. …
=> Use Cargo's build script metadata feature to make reliable include dirs

BUCK, BUILD, gen/build/Cargo.toml, gen/build/src/cfg.rs, gen/build/src/lib.rs, tests/BUCK, tests/BUILD, tests/ffi/build.rs, tests/ffi/lib.rs, tests/ffi/module.rs, tests/ffi/tests.cc, third-party/BUCK, third-party/BUILD, third-party/Cargo.lock, tools/bazel/rust_cxx_bridge.bzl
This PR adds a global configuration object called cxx_build::CFG.
<br>
- #### `CFG.include_prefix`
Presently the only exposed configuration is the `include_prefix`, the prefix at which C++ code from your crate as well as directly dependent crates can access the code generated during this build.
By default, the `include_prefix` is equal to the name of the current crate. That means if our crate is called `demo` and has Rust source files in a *src/* directory and maybe some handwritten C++ header files in an *include/* directory, then the current crate as well as downstream crates might include them as follows:
```cpp
// include one of the handwritten headers:
#include "demo/include/wow.h"
// include a header generated from Rust cxx::bridge:
#include "demo/src/lib.rs.h"
```
By modifying …
=> Expose control of import prefix to Cargo builds

gen/src/write.rs, macro/src/expand.rs, syntax/check.rs, syntax/ident.rs, syntax/mangle.rs, syntax/mod.rs, syntax/parse.rs, syntax/types.rs
As requested in https://github.com/dtolnay/cxx/pull/218#discussion_r502736645.
We'll want to do the same for all other types of items, but this PR just does functions as the immediate priority.
=> Store independent rust name and c++ name for extern functions

syntax/attrs.rs, syntax/parse.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
Supersedes #218.
Within cxx::bridge we can write #\[rust_name = "..."\] or #\[cxx_name = "..."\] to make a change to either name of a function.
In general many functions can have the same C++ name (due to overloading). Every function must continue to have a unique Rust name.
=> Support functions having distinct Rust name and C++ name

.github/workflows/ci.yml, WORKSPACE, third-party/BUILD, tools/bazel/rust.bzl, tools/bazel/vendor.bzl
This should make all bazel commands just work without needing to have run `cargo vendor --versioned-dirs third-party/vendor` manually beforehand.
It also updates third-party/Cargo.lock when required by changes to Cargo.toml.
=> Automatically run cargo vendor from bazel

tools/cargo/build.rs
Hello! I have just seen a crazy amount of work has gone into this crate since my last symlink problem https://github.com/dtolnay/cxx/pull/227 🙂
I was eager to test it out on Windows, and found a little corner case:
After a `git clone -c core.symlinks=false` and `cargo test`, the script outputs a Git error as expected:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
When building `cxx` from a git clone, git's symlink support needs
to be enabled on platforms that have it off by default (Windows).
Either use:
$ git config --global core.symlinks true
prior to cloning, or else use:
$ git clone -c core.symlinks=true https://github.com/dtolnay/cxx
for the clone.
Symlinks are only required when compiling locally from a clone of
the git repository---they are NOT required when …
```
=> Fix Windows symlink test to give reproducible error messages

gen/README.md, gen/lib/src/lib.rs, gen/src/include.rs
At present, this file is available only from the git repository,
but higher level code generators may wish to ensure that they supply
a version of `cxx.h` corresponding precisely to the version of cxx
in use.
Specifically, such higher level code generators may wish to use
`rust::Str` and similar types in code which _they_ autogenerate,
and thus need a way to include definitions of such types. As
this code is autogenerated, it can't reasonably rummage around
the cxx git repository to find the correct `cxx.h` header.
To be even more specific, higher level code generators may wish
to pass `rust::Str` and/or `rust::String` types into C++, in order
to create `UniquePtr<CxxString>`s from Rust strings during function
calls.
=> Make cxx.h available to high level code generators.

gen/build/src/lib.rs, gen/cmd/src/main.rs, gen/src/check.rs, gen/src/mod.rs, syntax/error.rs
```console
error[cxxbridge]: #include relative to `.` or `..` is not supported in Cargo builds
┌─ src/main.rs:10:18
│
10 │         include!("../header.h");
│                  ^^^^^^^^^^^^^ #include relative to `.` or `..` is not supported in Cargo builds
│
= note: use a path starting with the crate name
```
Closes #368.
=> Check for disallowed include strings in Cargo-based workflow

syntax/check.rs, syntax/error.rs
First commit is extracted from #370.
<pre>
<b>error[cxxbridge]: unsupported type: OsString</b>
┌─ src/main.rs:15:21
│
15 │         fn huh(wtf: <b>OsString</b>);
│                     <b>^^^^^^^^ unsupported type</b>
</pre>
=> Include typename in diagnostic on unsupported type

gen/src/mod.rs, gen/src/namespace_organizer.rs, gen/src/out.rs, gen/src/write.rs, macro/src/expand.rs, syntax/atom.rs, syntax/attrs.rs, syntax/check.rs, syntax/ident.rs, syntax/impls.rs, syntax/mangle.rs, syntax/mod.rs, syntax/parse.rs, syntax/qualified.rs, syntax/symbol.rs, syntax/tokens.rs, syntax/types.rs, tests/BUCK, tests/BUILD, tests/ffi/build.rs, tests/ffi/class_in_ns.rs, tests/ffi/extra.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs, tests/ui/by_value_not_supported.stderr
This PR consists of lots of commits adding tests, then a commit which actually achieves it.
It should achieve points 1-3 on the plan in #353, and most of #​4 (it doesn't currently look for namespace attributes on `extern` blocks but the rest is done).
Obsoletes #369.
=> Allow namespace override

include/cxx.h, src/cxx.cc
This enables the System V ABI to pass them in registers. See page 20 of https://software.intel.com/sites/default/files/article/402129/mpx-linux64-abi.pdf.
> If a C++ object has either a non-trivial copy constructor or a non-trivial destructor<sup>11</sup>, it is passed by invisible reference (the object is replaced in the parameter list by a pointer that has class POINTER)<sup>12</sup>.
>
> An object with either a non-trivial copy constructor or a non-trivial destructor cannot be passed by value because such objects must have well defined addresses. Similar issues apply when returning an object from a function.
Repro:
```cpp
const char *ptr(rust::Str str) { return str.repr.ptr; }
size_t len(rust::Str str) { return str.repr.len; }
```
Before:
```asm
ptr(rust::Str):
mov     rax, qword ptr …
```
=> Guarantee trivial copy constructor and destructor for Str and Slice

gen/src/write.rs, include/cxx.h, src/cxx.cc
It was misleading to use `Str` (which ordinarily represents borrowed strings) also for owned error messages.
=> Decouple Error from Str::Repr

src/cxx.cc
Otherwise these would be default-constructing the base class. Unclear if this makes a difference for any real std::exception implementation but might as well.
=> Fill in Error base class constructor calls

gen/src/write.rs, include/cxx.h, src/cxx.cc, tests/cxx_gen.rs
Since #387, `rust::Str` has an ABI that matches our Rust struct `cxx::rust_str::RustStr`, and since #388 `Error` doesn't need it either. That leaves no more need for `Str::Repr` as a separate type.
=> Eliminate Str::Repr struct

macro/src/expand.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
=> Fix fn arg representation to eliminate warning on rust 1.46+

gen/src/mod.rs
=> Collect apis from multiple cxx::bridge in the same file

gen/src/block.rs, gen/src/builtin.rs, gen/src/mod.rs, gen/src/out.rs, gen/src/write.rs
Stack of refactors incoming.
This is in preparation for a topological sort (#292), which will require relatively unstructured jumping between namespaces.
=> Preserve meaning of block boundaries

gen/src/write.rs
Made possible by #404. This begins ditching `NamespaceEntries`'s namespace-sorted order. For implementing a topological sort of the data structures, dealing with a single flat Vec of `Api`s is going to be a lot easier than a tree of `NamespaceEntries`.
=> Emit data structures and functions in source order

gen/src/builtin.rs, gen/src/write.rs, include/cxx.h
```cpp
// IsRelocatable<T> is used in assertions that a C++ type passed by value
// between Rust and C++ is soundly relocatable by Rust.
//
// There may be legitimate reasons to opt out of the check for support of types
// that the programmer knows are soundly Rust-movable despite not being
// recognized as such by the C++ type system due to a move constructor or
// destructor. To opt out of the relocatability check, do either of the
// following things in any header used by `include!` in the bridge.
//
//      --- if you define the type:
//      struct MyType {
//        ...
//    +   using IsRelocatable = std::true_type;
//      };
//
//      --- otherwise:
//    + template <>
//    + struct rust::IsRelocatable<MyType> : std::true_type {};
struct IsRelocatable;
``` …
=> Expose way to bypass trivial destr/move on extern types passed by value

macro/src/expand.rs, syntax/improper.rs, syntax/mod.rs, syntax/types.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
Fixes #249.
Previously:
```rust
#[repr(C)]
pub struct SharedString {
pub msg: String,
}
```
```console
error: `extern` block uses type `std::string::String`, which is not FFI-safe
--> tests/ffi/lib.rs:176:40
|
176 |         fn c_take_ref_shared_string(s: &SharedString) -> &SharedString;
|                                        ^^^^^^^^^^^^^ not FFI-safe
|
= note: this struct has unspecified layout
error: `extern` block uses type `std::string::String`, which is not FFI-safe
--> tests/ffi/lib.rs:176:58
|
176 |         fn c_take_ref_shared_string(s: &SharedString) -> &SharedString;
|                                                          ^^^^^^^^^^^^^ not FFI-safe
|
= note: this struct has unspecified layout
```
=> Pass improper ctype references by void pointer

gen/src/error.rs
Before:
<pre>
$  <b>echo '#[cxx::bridge] mod ffi { extern "Swift" {} }' | cxxbridge -</b>
error[cxxbridge]: unrecognized ABI
┌─ -:1:26
│
1 │ #[cxx::bridge] mod ffi { <b>extern "Swift"</b> {} }
│                          <b>^^^^^^^^^^^^^^ unrecognized ABI</b>
</pre>
After:
<pre>
$  <b>echo '#[cxx::bridge] mod ffi { extern "Swift" {} }' | cxxbridge -</b>
error[cxxbridge]: unrecognized ABI
┌─ /dev/stdin:1:26
│
1 │ #[cxx::bridge] mod ffi { <b>extern "Swift"</b> {} }
│                          <b>^^^^^^^^^^^^^^ unrecognized ABI</b>
</pre>
=> Fix filename in diagnostics when taking input from stdin

syntax/set.rs, syntax/types.rs
Having a newtype here avoids introducing accidental iteration over sets what are not meant to be iterated over. See https://github.com/dtolnay/cxx/pull/368#discussion_r511539163.
=> Introduce UnorderedSet newtype

gen/build/src/deps.rs, gen/build/src/lib.rs
Necessary for implementing `CFG.exported_header_prefixes` and `CFG.exported_header_links` (#417).
=> Track include_prefix and links attribute across deps

gen/build/src/deps.rs, gen/build/src/lib.rs
In preparation for adding `CFG.exported_header_dirs` to the exported headers (#417).
=> Preserve more than just the two default exported dirs

gen/build/src/error.rs, gen/build/src/lib.rs
Part of #417.
The field is still #\[doc(hidden)\] for now but documentation will follow after implementing the other two new fields of CFG in #417.
=> Implement CFG.exported_header_dirs

gen/build/src/deps.rs, gen/build/src/lib.rs
For now every header dir in this data structure is set to exported = true, but we'll be starting to add header dirs from dependencies as part of #417 and those may either be exported or private depending on `CFG.exported_header_prefixes` and `CFG.exported_header_links`.
=> Track visibility of exported headers

tests/ui/result_no_display.rs, tests/ui/result_no_display.stderr
The placement of this error is not good. In an extern "Rust" block with a large number of signatures it's hard to tell which one is returning the problematic error type. Will follow up to fix this after a refactor.
=> Add ui test of returning a non-displayable error

macro/src/expand.rs, tests/ffi/lib.rs, tests/ui/missing_unsafe.rs, tests/ui/missing_unsafe.stderr, tests/ui/result_no_display.stderr, tests/ui/unsupported_elided.rs, tests/ui/unsupported_elided.stderr
Previously we were accepting extern Rust declarations like the following, which is problematic because it makes it hard for a caller in C++ to see clearly when they hold responsibility for additional invariants.
```rust
fn f();
}
...
unsafe fn f() {...}
```
=> Enforce accurate unsafety declaration on extern Rust sigs

gen/src/write.rs, tests/ffi/lib.rs, tests/ffi/tests.cc
=> Fix placement of commas in C++ member functions that call Rust methods

syntax/file.rs, syntax/parse.rs
This is called out in #370 as not implemented yet.
> It should achieve points 1-3 on the plan in #353, and most of #​4 (it doesn't currently look for namespace attributes on `extern` blocks but the rest is done).
This PR implements `#[namespace = "..."]` attributes on extern blocks, such that an item will inherit the namespace specified on its surrounding extern block if any, otherwise the namespace specified with the top level cxx::bridge attribute.
```rust
#[cxx::bridge(namespace = "third_priority")]
mod ffi {
#[namespace = "second_priority"]
fn f();
#[namespace = "first_priority"]
fn g();
}
fn h();
}
}
```
The above would result in functions `::second_priority::f`, `::first_priority::g`, `::third_priority::h`.
=> Parse namespace attribute on foreign mods

gen/src/builtin.rs, include/cxx.h
Even though the generated code does not use them, this avoids a situation where the user's code includes a generated header (but not rust/cxx.h) and thus gets the class definition of rust::Fn, but with the function call operator templates undefined. Previously they'd have gotten missing template errors until they also included rust/cxx.h.
=> Provide rust::Fn call operator in generated header

gen/src/builtin.rs, gen/src/write.rs, include/cxx.h, macro/src/expand.rs, src/cxx.cc, src/rust_vec.rs, src/symbols/rust_vec.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
These APIs match std::vector.
```diff
class Vec final {
public:
...
+   void reserve(size_t new_cap);
+   void push_back(const T &value);
+   void push_back(T &&value);
+   template <class... Args>
+   void emplace_back(Args &&... args);
};
```
Part of #149.
=> Add rust::Vec push_back and emplace_back

src/lib.rs
Noticed this helpful new warning pop up recently from rustdoc. Apparently this syntax has worked for a while, at least since Rust 1.25.
```console
warning: unneeded long form for URL
--> src/lib.rs:61:5
|
61 | //! [https://github.com/dtolnay/cxx]. To try it out, run `cargo run` from that
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/dtolnay/cxx>`
|
= note: `#[warn(non_autolinks)]` on by default
warning: unneeded long form for URL
--> src/lib.rs:256:43
|
256 | //! built from the *gen/cmd* directory of [https://github.com/dtolnay/cxx].
|                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://github.com/dtolnay/cxx>`
warning: unneeded long form for URL
--> src/lib.rs:331:8
| …
```
=> Switch to short form url links in rustdoc

README.md, gen/lib/tests/test.rs, macro/src/lib.rs, src/exception.rs, src/extern_type.rs, src/lib.rs, syntax/parse.rs, tests/cxx_gen.rs, tests/ffi/extra.rs, tests/ffi/lib.rs, tests/ffi/module.rs, tests/ui/by_value_not_supported.rs, tests/ui/disallow_lifetime.rs, tests/ui/include.rs, tests/ui/reference_to_reference.rs, tests/ui/reserved_name.rs, tests/ui/unique_ptr_to_opaque.rs, tests/ui/unique_ptr_twice.rs, tests/ui/unnamed_receiver.rs, tests/ui/unrecognized_receiver.rs, tests/ui/wrong_type_id.rs
This is the non-breaking part factored out of #454.
=> Update cxx::bridge modules to use extern "C++" as the ABI

syntax/parse.rs, tests/ui/multiple_parse_error.stderr
We previously compromised in accepting `extern "C"` due to an unfortunate rustfmt bug that caused rustfmt to blindly replace any unrecognized ABI with `extern "Rust"` (https://github.com/rust-lang/rustfmt/issues/4086).
Closes #137.
=> Enforce use of extern "C++" as the ABI string

build.rs
This isn't so useful at the moment, but will be important after #456 since that change is going to require the most recent stable version of the compiler.
---
=> Warn on unsupported rust toolchain version

.github/workflows/site.yml
This brings in the following PRs I made upstream which are not yet in an mdbook release:
- https://github.com/rust-lang/mdBook/pull/1375 ***Fix stray spacing after #playground code***
- https://github.com/rust-lang/mdBook/pull/1376 ***Escape \`<\` and \`>\` in rendered toc to match handlebars' escaping in \<title\>***
- https://github.com/rust-lang/mdBook/pull/1379 ***Add hidelines code class to enable hiding in non-Rust blocks***
- https://github.com/rust-lang/mdBook/pull/1381 ***Add page title override: {{#title My Title}}***
The package is built from https://github.com/dtolnay/mdBook/tree/cxx.
=> Pull in unreleased mdbook fixes

book/package-lock.json, book/package.json
Our use of things like `Vec&lt;T&gt;` in rendered markdown is affected by this bug in cheerio v1.0.0-rc: https://github.com/cheeriojs/cheerio/issues/1370. What should be a lossless round-trip ends up mangling the data to `Vec<T>` which is invalid HTML.
```js
const f = fs.readFileSync(path, 'utf8');
const $ = cheerio.load(f, { decodeEntities: false });
fs.writeFileSync(path, $.html());
```
Downgrading to the previous release fixes the issue.
=> Downgrade to cheerio 0.22

src/cxx_string.rs, src/cxx_vector.rs, src/opaque.rs, tests/ui/opaque_autotraits.rs, tests/ui/opaque_autotraits.stderr
This is necessary in order for `Pin<&mut Opaque>` to be meaningful. Otherwise it behaves just like `&mut Opaque` which may not be correct.
=> Ensure opaque types are !Unpin

gen/build/src/lib.rs, gen/cmd/src/main.rs, gen/lib/src/lib.rs, macro/src/expand.rs, macro/src/lib.rs, src/unique_ptr.rs, syntax/check.rs, syntax/impls.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs, tests/ffi/lib.rs, tests/ffi/module.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs, tests/ui/pin_mut_opaque.rs, tests/ui/pin_mut_opaque.stderr
Without this, it's possible for Rust code to obtain two different `&mut T` to an opaque extern C++ type `T` and do something like e.g. [swap](https://doc.rust-lang.org/std/mem/fn.swap.html) them, which shouldn't work because Rust does not have the size of the underlying C++ `T`.
=> Enforce mutable references to opaque extern C++ types are pinned

syntax/parse.rs, tests/ui/async_fn.rs, tests/ui/async_fn.stderr
Direct async fn support is tracked in https://github.com/dtolnay/cxx/issues/138. For now this just gives it a more useful error message than before.
=> Improve async fn error message with link to workaround

tests/ffi/extra.rs, tests/ffi/module.rs
The relevant rustfmt fixes:
- https://github.com/rust-lang/rustfmt/pull/4423
- https://github.com/rust-lang/rustfmt/pull/4433
- https://github.com/rust-lang/rustfmt/pull/4164
were backported to rustfmt 1.x in:
- https://github.com/rust-lang/rustfmt/pull/4434
- https://github.com/rust-lang/rustfmt/pull/4447
then that was brought into the Rust dist by:
- https://github.com/racer-rust/racer/pull/1132
- https://github.com/rust-lang/rls/pull/1701
- https://github.com/rust-lang/rust/pull/77590
and backported to beta:
- https://github.com/rust-lang/rust/pull/77705
in time for Rust 1.48, so rustfmt is able to handle this syntax now as of the most recent Rust release and I am comfortable removing the skips.
=> No longer need rustfmt::skip when using extern type alias

syntax/types.rs, tests/ffi/lib.rs
This fixes an error when an extern struct or enum is used as a struct field or function argument. Previously that would fail:
```console
error[cxxbridge]: needs a cxx::ExternType impl in order to be used as a field of `Second`
┌─ lib.rs:222:9
│
222 │         type COwnedEnum;
│         ^^^^^^^^^^^^^^^ needs a cxx::ExternType impl in order to be used as a field of `Second`
```
which is wrong because the bridge should know it itself is producing a compatible ExternType impl for the struct/enum.
=> Skip ExternType::Kind check if type is known trivial

gen/src/write.rs
Without this, something that is not an enum could have been able to pass our assertions, resulting in unpredictable behavior.
```rust
// rust
enum FakeEnum { K = 1usize }
extern "C++" { type FakeEnum; }
```
```cpp
// c++
struct FakeEnum {
static const int K = 1;
const char *x;
};
```
There may be valid reasons to want something of this nature to work, but forbid for now and someone will need to bring forward a concrete use case for consideration.
=> Check std::is_enum on extern enum

src/unique_ptr.rs, tests/ui/unique_ptr_as_mut.stderr
This is sound because UniquePtr\<T\> follows the pinning invariants of Pin\<Box\<T\>\>, which provides DerefMut under the same condition. In practice for CXX this impl will apply to UniquePtr of shared structs, and will not apply to UniquePtr of opaque C++ types.
=> Add conditional DerefMut for UniquePtr

.github/workflows/ci.yml, WORKSPACE
#456 had pulled in beta temporarily for the `unsafe extern` block language feature, but that's now available in stable 1.48.0.
=> Update CI to use stable 1.48.0 compiler

gen/src/write.rs, syntax/check.rs, syntax/impls.rs, syntax/improper.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs, syntax/types.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/test.rs
Address #458 
It translates 
```rust
#[cxx::bridge]
mod ffi {
struct Foo {
a: [i32; 0xf],
b: [Vec<usize>; 3_2],
}
}
```
to
```cpp
struct Foo final {
std::array<int32_t, 15> a;
std::array<rust::Vec<size_t>, 32> b;
};
```
The current implementation requires:
1. The size field must be an integer literal
2. The literal should be able to parse to usize
3. The type needs to be one of primitive type, shared struct, RustBox, RustVec, CxxVector, UniquePtr
I'm not sure if we can simply replace `[usize; 16]` to `std::array<uint64_t, 16>`.
=> Allow array inside shared struct definition

syntax/parse.rs
Unclear what this is left over from. Something in #370.
=> Remove redundant namespaces passed around by parser

gen/src/builtin.rs, gen/src/write.rs
We need a real definition for T, not just a forward declaration, when binding std::unique_ptr\<T\> because the Rust UniquePtr's Drop impl needs to be able to call ~unique_ptr which needs to call ~T. Among other things, the C++ compiler needs to be able to determine whether ~T is public, which needs a type definition available.
```rust
#[cxx::bridge]
mod ffi {
include!("test/include/test.h");
type Opaque;
fn f() -> UniquePtr<Opaque>;
}
}
```
```cpp
#pragma once
#include <memory>
struct Opaque;
std::unique_ptr<Opaque> f() noexcept;
```
```console
In file included from /usr/include/c++/9/memory:80,
from target/debug/build/example-8b477c085d2b5f88/out/cxxbridge/crate/test/include/test.h:2,
from target/debug/build/example-8b477c085d2b5f88/out/cxxbridge/sources/test/src/mai …
```
=> Improve error message on unique_ptr of incomplete forward declared type

gen/src/error.rs
Improves the message in https://github.com/dtolnay/cxx/issues/119#issuecomment-733901382.
Before: `cxxbridge: no #[cxx::bridge] module found`
After: `cxxbridge: no #[cxx::bridge] module found in src/lib.rs`
=> Include filepath in no-bridge-found error

syntax/parse.rs, tests/ui/array_len_expr.rs, tests/ui/array_len_expr.stderr
Previously only the first diagnostic among the fields would be emitted.
=> Allow simultaneous diagnostics on multiple fields of a struct

syntax/parse.rs, tests/ui/array_len_expr.rs, tests/ui/array_len_expr.stderr
C++ interprets these differently than Rust, causing potentially mismatching field offsets.
=> Disallow array with zero size

gen/src/builtin.rs, gen/src/write.rs, include/cxx.h
For use in static assertions via https://en.cppreference.com/w/cpp/types/is_base_of.
=> Add common base class for opaque Rust types

gen/src/write.rs, macro/src/derive.rs, macro/src/expand.rs, syntax/derive.rs, syntax/mangle.rs, tests/ffi/lib.rs, tests/ffi/tests.cc
Part of #109.
```rust
#[cxx::bridge]
mod ffi {
#[derive(PartialEq)]
struct Struct {
x: i32,
}
}
```
```cpp
// generated
struct Struct final {
int32_t x;
bool operator==(const Struct &) const noexcept;
bool operator!=(const Struct &) const noexcept;
};
```
=> Emit operator== for shared structs with derive(PartialEq)

gen/src/write.rs, macro/src/expand.rs, tests/ffi/lib.rs
The previous implementation from #518 wrongly assumed `operator!=` can be implemented as `!(*this == other)`. That's only the case if an `Eq` impl is present (in addition to the `PartialEq`). For example it is not true in the case of floats, which are PartialEq-only.
This PR adds a separate symbol for `operator!=` for types that may have no `Eq` impl.
=> Implement operator!= using a distinct symbol from operator==

gen/src/write.rs, macro/src/derive.rs, macro/src/expand.rs, syntax/derive.rs, tests/ffi/lib.rs
Part of #109. This adds `operator<`, `operator<=`, `operator>`, `operator>=` for shared structs that derive PartialOrd.
=> Support derive(PartialOrd, Ord)

gen/src/nested.rs, syntax/check.rs, syntax/mod.rs, syntax/parse.rs, tests/ui/extern_type_bound.rs, tests/ui/extern_type_bound.stderr
Relevant to the second and third bullet of #109. We'll be using these to connect C++ operators for opaque Rust types and Rust trait impls for opaque C++ types.
=> Parse trait bounded extern types

macro/src/expand.rs
=> Allow instance methods with same name on different types in same bridge

book/src/binding/str.md, book/src/binding/string.md, include/cxx.h, src/cxx.cc, tests/ffi/tests.cc
=> Add comparison operators for Str and String

syntax/check.rs, syntax/types.rs, tests/BUCK, tests/BUILD, tests/ffi/lib.rs, tests/ffi/module.rs, tests/ui/vec_opaque.rs, tests/ui/vec_opaque.stderr
=> Fix Vec containing shared type from other module

macro/src/expand.rs, src/lib.rs, src/rust_type.rs
This fixes a hole in the combination of #541 + #542 (which is why I'd excluded those PRs from the most recent release).
Without this restriction, the following crates would have typechecked but caused duplicate symbols which is UB:
```rust
// crate A
#[cxx::bridge]
mod ffi {
struct S { x: i32 }
}
```
```rust
// crate B which depends on A
#[cxx::bridge]
mod ffi {
extern "C++" {
type S = a::S;
}
impl Vec<S> {}
}
```
```rust
// crate C which depends on A
#[cxx::bridge]
mod ffi {
extern "C++" {
type S = a::S;
}
impl Vec<S> {}
}
```
The nonlocal types design described in https://github.com/dtolnay/cxx/issues/496#issuecomment-736253352 prohibits the code in crates B and C (`unsafe impl Vec<S>` would be required for a nonlocal type `S`) but is not implemented yet. For now this PR is a pretty …
=> Limit instantiation of Vec and Box shims to local element type

gen/src/include.rs, gen/src/write.rs
Otherwise:
```rust
#[cxx::bridge]
mod ffi {
#[derive(Hash)]
struct S { x: usize }
}
```
```console
example-2a7c49ac8bd0f12e/out/cxxbridge/sources/example/src/main.rs.cc:17:20: error: ‘hash’ is not a class template
17 | template <> struct hash<::S> {
|                    ^~~~
example-2a7c49ac8bd0f12e/out/cxxbridge/sources/example/src/main.rs.cc:17:30: error: explicit specialization of non-template ‘std::hash’
17 | template <> struct hash<::S> {
|                              ^
```
=> Include <functional> when deriving Hash impl shim

gen/src/write.rs
Fixes #551. *All* shared structs are safe to hold and pass around by value in both Rust and C++.
=> Mark all shared structs as relocatable

gen/src/write.rs, include/cxx.h, macro/src/expand.rs
This produces *maybe* a slightly better diagnostic, but more importantly the new arrangement is more amenable to fixing #570 because it makes it possible to run a T constructor prior to any rust::Box instance existing in C++ yet.
Before:
```console
src/example.cc: In function ‘void test()’:
src/example.cc:12:21: error: ‘rust::cxxbridge1::Box<T>::Box() [with T = Struct]’ is private within this context
12 |   rust::Box<Struct> box;
|                     ^~~
In file included from src/example.cc:1:
example-ecfac19134395bcc/out/cxxbridge/include/example/src/main.rs.h:145:1: note: declared private here
145 | Box<T>::Box() noexcept = default;
| ^~~~~~
```
After:
```console
src/example.cc: In function ‘void test()’:
src/example.cc:12:21: error: use of deleted function …
```
=> Delete private Box default constructor

include/cxx.h
Fixes part of #570. This still leaks if T's constructor throws but Rust considers that safe and it will be fixed separately.
=> Fix uninitialized Drop on exception in rust::Box<T>::in_place

src/cxx.cc
Rust specifies that usize is ABI compatible with C's uintptr_t: https://rust-lang.github.io/unsafe-code-guidelines/layout/scalars.html#isize-and-usize. However there is no direct Rust equivalent for size_t. C does not guarantee that size_t and uintptr_t are compatible. In practice though, on all platforms supported by Rust, they are identical for ABI purposes. See the libc crate which unconditionally defines libc::size_t = usize. We expect the same here and the assertions in this PR are just to explicitly document that.
**Note that no assumption is made about C++ name mangling of signatures containing these types, not here nor anywhere in CXX.**
=> Document and static assert assumptions on size_t layout

src/cxx_vector.rs, src/lib.rs, src/shared_ptr.rs, src/unique_ptr.rs
I'd like to use at least `cxx::vector` as a public module name to expose the `VectorElement` trait for #547.
=> Shorten name of string and vector modules

src/cxx_vector.rs, src/lib.rs
This change doesn't yet expose a VectorElement trait as needed by #547, but this module is where that would be exposed. For now the only newly accessible API is the shared reference iterator `cxx::vector::Iter` which matches the convention of how e.g. [`std::slice::Iter`](https://doc.rust-lang.org/std/slice/struct.Iter.html) and [`std::collections::hash_map::Iter`](https://doc.rust-lang.org/std/collections/hash_map/struct.Iter.html) are named.
=> Expose public vector module

src/cxx_vector.rs
The contract is that once it's returned None, it is guaranteed to continue returning None as many time as called again.
https://doc.rust-lang.org/std/iter/trait.FusedIterator.html
=> Mark CxxVector iterator as FusedIterator

syntax/check.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
=> Consider mut receiver for allowing mut C++ return type

gen/src/write.rs, syntax/check.rs, syntax/types.rs, tests/ffi/module.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs, tests/ui/by_value_not_supported.stderr, tests/ui/pin_mut_opaque.stderr
=> Allow un-pinned Trivial extern types to be passed by reference as arguments

gen/src/write.rs, macro/src/expand.rs, src/cxx.cc, src/cxx_vector.rs
```diff
impl<T> CxxVector<T> {
...
+     pub fn get_mut(&mut self, pos: usize) -> Option<Pin<&mut T>>;
+     pub unsafe fn get_unchecked_mut(&mut self, pos: usize) -> Pin<&mut T>;
}
```
=> Add mutable indexing for CxxVector

gen/src/write.rs, macro/src/expand.rs, tests/ui/opaque_not_sized.stderr
The generated code looks like:
```rust
// input
#[cxx::bridge]
mod ffi {
type MyStruct;
}
}
```
```cpp
// generated
struct MyStruct final : public ::rust::Opaque {
private:
struct layout {
static ::std::size_t size() noexcept;
static ::std::size_t align() noexcept;
};
};
```
The accessors are private so it's not directly usable right away but I'll be adding some `friend` items in a separate PR which builds on top of these.
=> Emit private layout struct for all opaque types

macro/src/expand.rs, tests/ui/opaque_not_sized.stderr
This works around some noise in the error message of tests/ui/opaque_not_sized.stderr introduced by #595.
=> Improve rustc diagnostic when an extern Rust type is unsized

gen/src/builtin.rs, gen/src/write.rs, include/cxx.h, tests/ffi/tests.cc
```diff
namespace rust {
+ template <typename T> size_t size_of();
+ template <typename T> size_t align_of();
}
```
Using `rust::size_of<T>()` / `rust::align_of<T>()` produces an accurate size/align for opaque Rust types (via the symbols from #595) as well as shared data structures and native C++ types.
Support for opaque Rust types in slices (#532) can be easily implemented on top of these.
=> Add rust::size_of, align_of accessors that work for opaque types

book/src/binding/slice.md, gen/src/builtin.rs, include/cxx.h, tests/ffi/tests.cc
```diff
class Slice {
public:
...
+   bool empty() const noexcept;
+   T &operator[](size_t n) const noexcept;
+   T &at(size_t n) const;
+   T &front() const noexcept;
+   T &back() const noexcept;
};
```
=> Add checked and unchecked indexing to rust::Slice

gen/src/builtin.rs, include/cxx.h
Part of #532, building on #597 and #600.
=> Obtain Slice iterator stride in a way that works for opaque types

gen/src/builtin.rs, include/cxx.h
Rust requires that references are always sufficiently aligned. We don't yet allow slices of opaque Rust types to exist on the language boundary, but once we do (#532), we will need empty slices instantiated by C++ to have sufficient alignment. Without this change, C++ would think `alignof(T)` is 1 for opaque Rust types and passing an empty slice from C++ to Rust would be UB if the real alignment were higher than 1.
=> Obtain accurate alignment for empty slice of opaque Rust type

gen/src/write.rs, include/cxx.h, macro/src/expand.rs, src/cxx.cc, src/symbols/rust_vec.rs
As of #597 we have a reliable C++ size accessor for all types, including opaque Rust types. Thus there's no longer a need for Vec shims to contain their own separate stride symbol.
=> Eliminate Vec stride symbol in favor of size_of

gen/src/builtin.rs, include/cxx.h
This exactly mirrors how the two iterators are handled in the Rust standard library. Both Vec\<T\>'s and &amp;\[T\]'s `iter()` method returns the same iterator type `std::slice::Iter`.
https://doc.rust-lang.org/std/vec/struct.Vec.html#method.iter
https://doc.rust-lang.org/std/primitive.slice.html#method.iter
Originally we had these as separate iterator types in CXX because `rust::Vec` supported opaque Rust types from the beginning since #148 while `rust::Slice` only much later since #603. Now that the two are in parity, we only need one of the iterator implementations.
=> Reuse Slice<T>'s iterator for Vec iteration too

book/src/shared.md
This functionality landed in [1.0.6](https://github.com/dtolnay/cxx/releases/tag/1.0.6) but hadn't made it to the website yet.
=> Document derive support in shared types page of website

gen/src/nested.rs, macro/src/expand.rs, syntax/check.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs
Part of #608.
An extern type `type Example<'a, 'b>;` turns into:
```rust
#[repr(C)]
pub struct Example<'a, 'b> {
_private: ::cxx::private::Opaque,
_lifetime_a: ::std::marker::PhantomData<&'a ()>,
_lifetime_b: ::std::marker::PhantomData<&'b ()>,
}
unsafe impl<'a, 'b> ::cxx::ExternType for Asdf<'a, 'b> {
type Id = ::cxx::type_id!("Example");
type Kind = ::cxx::kind::Opaque;
}
```
Note that we assume covariant lifetimes. It's possible we'll also expose contravariant and invariant lifetimes something like the `ghost` crate (https://github.com/dtolnay/ghost#variance).
=> Emit lifetimes on extern type into Rust macro output

gen/build/src/lib.rs
just a minor change to allow headers with extentions other than `.h` to used
=> add support for .hh and .hpp headers

gen/cmd/src/main.rs
This is the cxxbridge-cmd crate change corresponding to the cxx-build crate change from #613.
=> Recognize .hh and .hpp as header extensions in cxxbridge-cmd

gen/src/write.rs
Closes #612. Based on https://github.com/david-cattermole/cxx/commit/363c18b2982329d6e4fbc2a6e5f324f4fef03661.
=> Add C++ symbol visibility annotations for Rust functions and impls

tests/ui/deny_missing_docs.rs, tests/ui/deny_missing_docs.stderr
The spans on the resulting missing_docs lints from rustc are horrible... I will make some follow-up PRs to get that cleaned up preserving all the right spans.
=> Add ui test of missing_docs lints inside bridge

macro/src/expand.rs, syntax/mod.rs, syntax/parse.rs, tests/ui/deny_missing_docs.stderr
Part of improving #617.
Before:
```console
error: missing documentation for a struct
--> $DIR/deny_missing_docs.rs:9:1
|
9 | #[cxx::bridge]
| ^^^^^^^^^^^^^^
```
After:
```console
error: missing documentation for a struct
--> $DIR/deny_missing_docs.rs:11:5
|
11 |     pub struct UndocumentedStruct {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
=> Fix span placement on shared structs

gen/src/nested.rs, macro/src/expand.rs, syntax/attrs.rs, syntax/impls.rs, syntax/mod.rs, syntax/parse.rs, tests/ui/deny_missing_docs.rs, tests/ui/deny_missing_docs.stderr
https://doc.rust-lang.org/reference/attributes/diagnostics.html#lint-check-attributes
- `#[allow(...)]`
- `#[warn(...)]`
- `#[deny(...)]`
- `#[forbid(...)]`
=> Propagate rust lint control attributes into macro output

syntax/impls.rs, syntax/mod.rs, syntax/names.rs, syntax/tokens.rs, syntax/types.rs
=> Represent type names with generic lifetime parameters

gen/build/src/lib.rs
This results in slightly less noise when code generation produces an error during a Cargo build.
```console
process didn't exit successfully: `/git/example-cxx/target/debug/build/example-f20ef12178a95a23/build-script-build` (exit code: 1)
--- stdout
cargo:CXXBRIDGE_PREFIX=example
cargo:CXXBRIDGE_DIR0=/git/example-cxx/target/debug/build/example-188c8410ffc8bb7d/out/cxxbridge/include
cargo:CXXBRIDGE_DIR1=/git/example-cxx/target/debug/build/example-188c8410ffc8bb7d/out/cxxbridge/crate
--- stderr
error[cxxbridge]: extern type with lifetimes is not supported yet
┌─ src/main.rs:9:21
│
9 │         type Object<'a>;
│                     ^^ extern type with lifetimes is not supported yet
```
```console
process didn't exit successfully: `/git/example-cxx/target/debug/build/example-f20ef12178a95a23/b …
```
=> Defer Cargo links metadata printing until after code generation

syntax/check.rs, syntax/parse.rs, syntax/tokens.rs
=> Parse lifetimes on Ident type names

gen/src/write.rs, macro/src/expand.rs, syntax/impls.rs, syntax/instantiate.rs, syntax/mod.rs, syntax/types.rs
Part of #608. This is required in order to meaningfully recognize that e.g. `impl<'a> UniquePtr<Object<'a>> {}` is applicable to a type `Object<'b>` for some "different" lifetime.
=> Key impls by an enum rather than by Type

syntax/impls.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs
Part of #608. This ensures that parsing works for impls such as:
```rust
extern "C++" {
type Object<'a>;
}
impl<'a> UniquePtr<Object<'a>> {}
```
=> Parse generic params on impl block

gen/src/write.rs, macro/src/expand.rs, syntax/map.rs, syntax/mod.rs, syntax/resolve.rs, syntax/types.rs
As part of type checking we precompute an OrderedMap of all the explicit and implicit generic type instantiations that need to be emitted. This eliminates previous duplication of logic between the Rust code generator and C++ code generator (the diff is net -73) but more importantly this refactor will be necessary for #608 because it provides a place to attach information about generic lifetime parameters that go with each of these impls. The lifetime information will be added in a later PR.
=> Generate all explicit and implicit impls based on one map

gen/src/write.rs, macro/src/derive.rs, macro/src/expand.rs, syntax/ident.rs, syntax/impls.rs, syntax/mangle.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs
This enables adjusting fn arg variable names when the given name is a keyword in the other language, and unblocks supporting #\[rust_name = "..."\] and #\[cxx_name = "..."\] attributes on the fields of shared structs.
=> Track independent Rust/C++ names on struct fields and fn args

gen/src/nested.rs, gen/src/write.rs, syntax/attrs.rs, syntax/ident.rs, syntax/mod.rs, syntax/names.rs, syntax/parse.rs, syntax/symbol.rs
`ForeignName` has no ToTokens impl so it won't accidentally end up emitted anywhere by the Rust code generator. This is also going to be necessary in order to support C++ names containing whitespace (`unsigned int`) or non-alphanumeric characters (`operator++`), neither of which can be represented by a Rust `Ident`. Finally it's a good extension point for implementing #593.
=> Add ForeignName wrapper around non-Rust names

gen/src/write.rs, macro/src/expand.rs, syntax/mangle.rs, syntax/resolve.rs, syntax/types.rs
Part of #608. The lifetimes recorded by the name resolver will need to be emitted into the corresponding Rust impl blocks.
```rust
#[cxx::bridge]
mod ffi {
extern "C++" {
type Borrowed<'a>;
^^^^
fn demo<'b>(s: &'b str) -> UniquePtr<Borrowed<'b>>;
}
}
```
*turns into:*
```rust
unsafe impl<'a> UniquePtrTarget for Borrowed<'a> {...}
^^^^                             ^^^^
```
=> Record lifetimes associated with generic type instantiation

macro/src/expand.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs
Part of #608. This updates all Rust generated code when instantiating generic types containing lifetime parameters. This builds on the lifetimes collected by the name resolver in #634.
```rust
#[cxx::bridge]
mod ffi {
extern "C++" {
type Borrowed<'a>;
^^^^
fn demo<'b>(s: &'b str) -> UniquePtr<Borrowed<'b>>;
}
}
```
*turns into:*
```rust
unsafe impl<'a> UniquePtrTarget for Borrowed<'a> {...}
^^^^                             ^^^^
```
=> Parameterize shim trait impl blocks over lifetimes

gen/src/builtin.rs, gen/src/write.rs, tests/cxx_gen.rs
Extracted from #636 since it does not depend on #637.
=> Remove rust::Str repr conversion in C++

gen/src/write.rs, tests/ffi/tests.cc
Unblocks #636. MSVC fails to compile code like the following unless there is an explicit instantiation of the class template:
```cpp
class slice {};
//template class slice<int>;
extern "C" slice<int> repro() { return {}; }
```
Error:
```console
<source>(6): error C2526: 'repro': C linkage function cannot return C++ class 'slice<int>'
<source>(6): note: see declaration of 'slice<int>'
<source>(6): error C2562: 'repro': 'void' function returning a value
<source>(6): note: see declaration of 'repro'
Compiler returned: 2
```
=> MSVC workaround for "C linkage function cannot return C++ class"

gen/src/builtin.rs, gen/src/write.rs, include/cxx.h
These layout conversions between pod and non-pod were made obsolete by #387, as since then `rust::Str` and `rust::Slice<T>` are correctly implemented as pod.
=> Remove rust::Slice repr conversion in C++

gen/src/write.rs, tests/ffi/tests.cc
#637 in slightly more restricted form. Only *returning* un-instantiated class templates appears to be affected. For `rust::Slice` types that are only used in function arguments or struct fields, not function return values, MSVC does not need to be given the explicit template instantiation.
=> Restrict MSVC instantiation workaround to return positions only

gen/src/write.rs, tests/ffi/tests.cc
Fix for warning when running cargo test. When looking at the declarations in`include/cxx.h`, the types are defined as `class Str final` etc. This mismatch when compared to `lib.rs.cc` causes a compiler warning to be output.
```
warning: /Users/pickett/Documents/GitHub/cxx/target/debug/build/cxx-test-suite-de711daed7f2e46d/out/cxxbridge/sources/tests/ffi/lib.rs.cc:1256:10: warning: struct template 'Slice' was previously declared as a class template; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
warning: template struct ::rust::Slice<const char>;
warning:          ^
warning: /Users/pickett/Documents/GitHub/cxx/target/debug/build/cxx-test-suite-de711daed7f2e46d/out/cxxbridge/include/rust/cxx.h:146:7: note: previous use is here
warning: class …
```
=> Fix warning mismatching struct and class

.vscode/launch.json
First time using VS Code to develop and I found this config made it easier to jump into breakpoint debugging the cargo tests.
"Debug cargo tests" now shows up in the drop-down, and setting a breakpoint in CXX or rust correctly stops.
=> Include a launch config for cargo tests

book/src/binding/box.md, book/src/binding/slice.md, book/src/binding/str.md, book/src/binding/string.md, book/src/binding/vec.md, include/cxx.h, src/cxx.cc, tests/ffi/tests.cc
Fixes #58.
Adds `swap` members to each of `Slice`, `Str`, `Vec`, `Box`, and `String`. Also adds private friend functions so that Argument Dependent Lookup may function via the `using std::swap;` idiom.
=> Add swap members + ADL functions

include/cxx.h, src/cxx.cc, tests/ffi/tests.cc
Both of these types are "is_trivially_move_constructible" and "is_trivially_move_assignable", so the default std::swap would already correctly do exactly the same thing that these are doing.
We keep the custom swap on Box, String, Vec which are not trivially movable, their moves do stuff to the source object to move around ownership.
FYI @capickett
=> Remove Str and Slice swaps

src/result.rs
This is necessary in order to update rust::Str to match the layout of &amp;str (using the same techniques we do in rust::String to make it match the representation of String in Rust).
Part of the work on #608. Once we allow lifetimes in general, including in structs, it will be possible to have structs containing &amp;str where we can no longer rely on the code generator to reconcile the representation between the Rust side and C++ side the way we currently do for strs in function argument and function return position.
=> Decouple C++ exception representation from Rust str

include/cxx.h, src/cxx.cc, src/rust_str.rs, src/symbols/rust_str.rs
Part of the work on #608. Once we allow lifetimes in general, including in structs, it will be possible to have structs containing &str where we can no longer rely on the code generator to reconcile the representation between the Rust side and C++ side the way we currently do for strs in function argument and function return position.
=> Preserve &str's original Rust representation in C++

include/cxx.h, src/cxx.cc, src/rust_slice.rs, src/symbols/mod.rs, src/symbols/rust_slice.rs
#645, but for slices too.
Part of #608.
=> Preserve &[T]'s Rust representation in rust::Slice

gen/src/write.rs
I guess MSVC finds this important enough to emit warnings about otherwise.
```console
cxxbridge\sources\tests\ffi\lib.rs.cc(1220): warning C4624: 'tests::R': destructor was implicitly defined as deleted
```
=> Explicitly delete opaque Rust type destructors

syntax/check.rs
As of #645 and #647, these no longer need to be special case exclusions.
=> Enable slices and arrays containing str/slice

syntax/check.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/ui/extern_type_lifetime.rs, tests/ui/extern_type_lifetime.stderr
Closes #608 (with the help of the large number of other PRs linked to that issue).
=> Enable lifetimes on opaque C++ types

macro/src/expand.rs, syntax/check.rs, tests/ffi/lib.rs
=> Enable lifetimes on opaque Rust types

gen/src/write.rs
Cherry picked from https://github.com/david-cattermole/cxx/commit/d58c650847d1f734d1c09a4e87d50f5904f2c4f5. See https://github.com/dtolnay/cxx/issues/612#issuecomment-753544437.
> Annotations for symbol visibility (such as `__declspec(dllexport)` and `__attribute__((visibility("default")))`) is the primary use case. Such annotations are expected to be needed on declarations (headers) only, however forcing the annotations into the header file only is causes missing symbols. Therefore the fix is to force the annotations into both declaration (header files) and definition (source files).
=> Force annotation on all functions in both source and header files

syntax/parse.rs, tests/ui/function_with_body.rs, tests/ui/function_with_body.stderr
Fixes #656.
**Before:**
```console
error[cxxbridge]: unsupported foreign item
┌─ src/main.rs:4:9
│
4 │         fn f() {}
│         ^^^^^^^^^ unsupported foreign item
```
**After:**
```console
error[cxxbridge]: expected `;`
┌─ src/main.rs:4:16
│
4 │         fn f() {}
│                ^ expected `;`
```
=> Improve extern fn with body error message

macro/src/expand.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h
=> Implement lifetime elision for member function receivers

macro/src/expand.rs, syntax/tokens.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h
=> Implement lifetime elision inside of pins

gen/build/Cargo.toml, gen/cmd/Cargo.toml, gen/lib/Cargo.toml, third-party/BUCK, third-party/BUILD, third-party/Cargo.lock
This is to avoid a downstream dependency to depend on multiple versions of that crate.
=> Upgrade the dependency on codespan_reporting

.devcontainer/build.Dockerfile, .github/workflows/ci.yml, WORKSPACE, third-party/BUILD, tools/bazel/BUILD, tools/bazel/rust.bzl, tools/bazel/rust_cxx_bridge.bzl, tools/bazel/vendor.bzl
As of https://github.com/bazelbuild/rules_rust/commit/1fe23158e5316c17b2ee2a252ee7165c5d83cc93 the Bazel rust rules have been renamed from `io_bazel_rules_rust` to `rules_rust`. This PR updates the name here.
=> Updated Bazel Rust rules version

book/src/async.md
The first argument of the closure is actually the context, not the sender. Rename it to `context` to make it clearer. Was slightly confused the first time I read it.
=> Minor correction in the async example

WORKSPACE, tools/bazel/rust_cxx_bridge.bzl
Currently the `rust_cxx_bridge.bzl` has to be copied to the main repository (and edited) if it is to be used from a different repository than cxx's own one in Bazel. After giving the cxx repo a name and using the label with the repository name the bzl file is now usable from outside as well.
Thanks! :)
=> Make rust_cxx_bridge usable from other repositories

gen/build/Cargo.toml
This allows building in parallel when the feature is enabled.
I wanted to try cxx-build with a fairly large code base and am hoping this will speed up the build. I may end up resorting to some other tool/configuration, but I can't see any reason not to try this first.
=> Re-export cc's parallel feature for cxx-build

syntax/check.rs, tests/ui/enum_receiver.rs, tests/ui/enum_receiver.stderr
Update the syntax checker to print a more specific error when an enum is
used as a method receiver, rather than printing a misleading "unrecognized
receiver type" error.
This is done because C++ prohibits enums from having member functions.
Fixes #578
=> Clarify error for using enum as method receiver

src/cxx.cc, src/symbols/rust_vec.rs, tests/ffi/tests.cc
Like #706 but without symbol collision on non-macOS platforms. Closes #706. Closes #705.
=> Support for Vec<usize> and Vec<isize> on macOS

syntax/parse.rs, tests/ui/enum_match_without_wildcard.stderr
This gives error placement that is more consistent with rustc's ordinary placement of certain errors.
=> Move span of inherited pub to next consecutive token

macro/src/expand.rs, tests/ui/drop_shared.rs, tests/ui/drop_shared.stderr
Closes #708 as suggested in https://github.com/dtolnay/cxx/issues/708#issuecomment-777640627.
=> Disallow misleading Drop impl on shared types

include/cxx.h, src/cxx.cc
Closes #696.
All of these move assignments have sane and sound behavior in the `this == &other` case. The object ends up in a destructible but unspecified state, which is sufficient.
=> Remove self assignment checks from move assignment operators

flags/LICENSE-APACHE, flags/LICENSE-MIT
Other crates in this repo already include them, and it is a requirement (or at least a strong suggestion) for packaging it into Fedora.
=> Include license files in flags crate

src/cxx_string.rs, tests/cxx_string.rs
Closes #737.
This is implemented by delegation to `&[u8]`, as suggested.
I also implemented `PartialOrd<str>`  for `CxxString` and `PartialOrd<CxxString>` for `str`, since `PartialEq<str>` is already implemented for `CxxString` and vice versa. I added tests for comparisons between `str` and `CxxString`, just in case.
=> Implement Eq, Ord, PartialOrd, Hash for CxxString

syntax/check.rs, syntax/parse.rs
That error does not need to be fatal at parse time, because the parser still understands exactly what was written. We accumulate and emit it alongside other type errors that might be present in the same function signature.
Follow-up to #689.
=> Defer unsafety check for fn with ptr argument

.github/workflows/ci.yml
We have been using this approach on the serde repo since last year and it works well (https://github.com/serde-rs/serde/blob/v1.0.125/.github/workflows/ci.yml#L155). It's quite common for Clippy to have low-value lints that we are better off disabling, but a contributor is not necessarily equipped to decide whether to suppress or resolve a lint, and consequently a clippy CI job can end up encouraging PRs submitted with needless workarounds.
=> Disable lint jobs on pull requests

.clang-tidy, .github/workflows/ci.yml
This adds a suppression for cppcoreguidelines-pro-type-vararg which appears newly in 11. I don't understand why this specific lint is triggering in the two cases below but the code seems fine in both cases.
```console
include/cxx.h:882:3: error: do not declare variables of type va_list; use variadic templates instead [cppcoreguidelines-pro-type-vararg,-warnings-as-errors]
auto data = reinterpret_cast<char *>(this->data());
^
src/cxx.cc:355:3: error: do not declare variables of type va_list; use variadic templates instead [cppcoreguidelines-pro-type-vararg,-warnings-as-errors]
char *copy = new char[len];
^
```
=> Update to clang-tidy 11

macro/src/expand.rs, src/cxx_vector.rs, src/fmt.rs, src/lib.rs, src/shared_ptr.rs, src/unique_ptr.rs, src/weak_ptr.rs
Fixes #759. This implements a different way of building type names for error messages which does not expect the 'static bound.
=> Support non-static vector element types inside of unique ptr

src/cxx_vector.rs, src/lib.rs, src/unique_ptr.rs, src/vector.rs
This keeps the focus on types that aren't already available at a more concise path, and avoids duplicating documentation for this type across 2 different URLs (https://docs.rs/cxx/1.0.34/cxx/struct.CxxVector.html vs https://docs.rs/cxx/1.0.34/cxx/vector/struct.CxxVector.html).
<br>
<br>
=> No-inline documentation of CxxVector within cxx::vector module

macro/src/expand.rs, src/cxx_vector.rs, src/lib.rs, src/memory.rs, src/shared_ptr.rs, src/unique_ptr.rs, src/vector.rs, src/weak_ptr.rs, tests/ui/unique_ptr_twice.stderr
These trait bounds enable manipulating UniquePtr, SharedPtr, and CxxVector inside of generic code.
Example:
```rust
use cxx::memory::{UniquePtr, UniquePtrTarget};
use std::fmt::Display;
pub fn take_generic_ptr<T>(ptr: UniquePtr<T>)
where
T: UniquePtrTarget + Display,
{
println!("the unique_ptr points to: {}", *ptr);
}
```
Writing the same generic function without a UniquePtrTarget trait bound would not compile.
Closes #685.
=> Make memory and vector trait bounds publicly nameable

gen/src/builtin.rs, gen/src/include.rs
Closes #703. Builtins are not dumped into the generated output file if *either* the #\[cxx::bridge\] module contains `include!("rust/cxx.h")` *or* the cxxbridge CLI is invoked to pass it as an additional include via `--include rust/cxx.h`.
**Before:**
```console
$ echo '#[cxx::bridge] mod ffi { struct Test { s: String } }' | cxxbridge /dev/stdin
#include <array>
#include <cstdint>
#include <string>
#include <type_traits>
namespace rust {
inline namespace cxxbridge1 {
// #include "rust/cxx.h"
#ifndef CXXBRIDGE1_RUST_STRING
#define CXXBRIDGE1_RUST_STRING
class String final {
...
...
...
};
#endif // CXXBRIDGE1_RUST_STRING
} // namespace cxxbridge1
} // namespace rust
struct Test;
#ifndef CXXBRIDGE1_STRUCT_Test
#define CXXBRIDGE1_STRUCT_Test
struct Test final {
::rust::String s;
using …
```
=> Omit most builtins if bridge explicitly includes "rust/cxx.h"

syntax/check.rs, tests/ui/ptr_unsupported.stderr
Vectors have elements, not targets. (Pointers, like unique_ptr and shared_ptr, have targets -- matching the terminology of Target in the [std::ops::Deref](https://doc.rust-lang.org/std/ops/trait.Deref.html) trait.)
=> Fix wording of unsupported vector element type error

syntax/mod.rs, syntax/types.rs, syntax/visit.rs
This is going to be necessary for recursive traversal of function argument types for #765.
The structure of the `Visit` trait exactly matches the design from [`syn::visit`](https://docs.rs/syn/1.0.65/syn/visit/index.html).
=> Factor out Type traversal to a Visit trait

syntax/check.rs, tests/ui/mut_return.rs, tests/ui/mut_return.stderr
=> Allow mutable return reference on signatures with any lifetime in argument

syntax/check.rs
This was made obsolete by support for explicit lifetime annotations in cxx 1.0.26 (#608).
Closes #764.
=> Remove multiple arg lifetimes check

syntax/improper.rs
=> Add a void ptr cast for extern type aliases containing Rust-native types

gen/src/write.rs, macro/src/expand.rs, macro/src/generics.rs, macro/src/lib.rs, syntax/instantiate.rs, syntax/mod.rs, syntax/resolve.rs, syntax/types.rs, tests/ui/nonlocal_rust_type.rs, tests/ui/nonlocal_rust_type.stderr
```rust
pub struct MyBuilder<'a> {
_s: &'a str,
}
type OptBuilder<'a> = Option<MyBuilder<'a>>;
#[cxx::bridge]
mod ffi {
type OptBuilder<'a>;
}
struct MyBuilder<'a> {
rs: Box<OptBuilder<'a>>,
}
}
```
Arrows everywhere, completely confused spans.
```console
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
--> $DIR/nonlocal_rust_type.rs:7:1
|
7  |   #[cxx::bridge]
|   ^^^^^^^^^^^^^^ impl doesn't use only types from inside the current crate
...
10 |           type OptBuilder<'a>;
|  ___________________________-
11 | |     }
12 | |
13 | |     struct MyBuilder<'a> {
14 | |         rs: Box<OptBuilder<'a>>,
| |__________________________- `Option` is not defined in the current crate
|
= note: define and implement a trait or new type …
```
=> Improve span of errors on implicitly generated shim impls

macro/src/expand.rs
This is a purely internal thing for cxx and doesn't need to be featured as a user-facing API on the type's rendered rustdoc page.
=> Hide extern "Rust" types' RustType impl from rustdoc

include/cxx.h
According to https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety:
> `data` must be non-null and aligned even for zero-length slices. One reason for this is that enum layout optimizations may rely on references (including slices of any length) being aligned and non-null to distinguish them from other data.
=> Debug assert that rust::Slice isn't constructed with C++ null ptr

include/cxx.h
Followup / relaxation of #788. This matches what we do for rust::String and rust::Str construction from ptr/len.
https://github.com/dtolnay/cxx/blob/72b8b7e5a2cde8378dcbbb7cecadf8fcd18f16c7/src/cxx.cc#L96-L101
https://github.com/dtolnay/cxx/blob/72b8b7e5a2cde8378dcbbb7cecadf8fcd18f16c7/src/cxx.cc#L214-L219
=> Allow slice null ptr safely if slice is empty

Cargo.toml, demo/Cargo.toml
By using a `patch` at the workspace root rather than path dependencies in the demo crate, the demo crate's dependencies can now match exactly what is shown/discussed in https://cxx.rs/tutorial.html and can be copied directly into the reader's project.
=> Make demo crate's Cargo dependencies copy/pasteable

gen/src/builtin.rs, gen/src/include.rs
This exception type is used for checked indexing of rust::Slice and rust::Vec, for example the following. it is provided by the `stdexcept` header.
https://github.com/dtolnay/cxx/blob/9b8ed98c33f11a8545b022641620f0de86c51b4c/include/cxx.h#L543-L549
https://en.cppreference.com/w/cpp/error/out_of_range
=> Include <stdexcept> for std::out_of_range type

syntax/check.rs, syntax/resolve.rs
The previous implementation contained calls to `Types::resolve` which could fail if the signature contained any unrecognized type name, such as a typo. `Types::resolve` is really only safe to call *after* all type checking has been completed, such as in gen/src/write.rs and macro/src/expand.rs.
This indicates maybe we should separate out a second "tier" of checks which only run after all names are known to successfully resolve.
=> Handle unrecognized type names in checking signature for mutable return type

syntax/check.rs, tests/ui/mut_return.rs, tests/ui/mut_return.stderr
Fixes #766.
See https://github.com/novifinancial/rust-plasma/pull/3 and https://github.com/MWATelescope/Birli/pull/1 for two examples of the type of unsound signature that this catches.
=> Recognize mutable slice in return position of a safe function

gen/build/Cargo.toml, gen/cmd/Cargo.toml, gen/lib/Cargo.toml, macro/Cargo.toml, third-party/BUCK, third-party/BUILD, third-party/Cargo.lock
Pulls in https://github.com/dtolnay/syn/pull/1006 + https://github.com/alexcrichton/proc-macro2/pull/283.
<br>
```console
error[cxxbridge]: lex error
┌─ src/main.rs:1:1
│
1 │ //! this file contains a lex error... where?
│ ^ lex error
```
```console
error[cxxbridge]: lex error
┌─ src/main.rs:46:12
│
46 │ fn main() {)
│            ^ lex error
```
=> Update to proc-macro2 with lex error spans

macro/src/generics.rs, tests/ui/expected_named.rs, tests/ui/expected_named.stderr
Fixes #805.
```console
error: expected one of `!`, `(`, `+`, `::`, `<`, `where`, or `{`, found `'a`
--> $DIR/expected_named.rs:4:23
|
4 |         type Borrowed<'a>;
|                       ^^ unexpected token
5 |         fn borrowed() -> UniquePtr<Borrowed>;
|                                            - expected one of 7 possible tokens
```
```console
error[E0106]: missing lifetime specifier
--> $DIR/expected_named.rs:5:36
|
5 |         fn borrowed() -> UniquePtr<Borrowed>;
|                                    ^^^^^^^^ expected named lifetime parameter
|
= help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime
|
5 |         fn borrowed() -> UniquePtr<Borrowed<'static>>;
| …
```
=> Fill in angle brackets with appropriate span if elided from impl key

gen/src/check.rs, gen/src/mod.rs, macro/src/expand.rs, syntax/check.rs, syntax/error.rs, tests/ui/reserved_lifetime.rs, tests/ui/reserved_lifetime.stderr
=> Diagnostic for invalid use of 'static as a lifetime parameter name

include/cxx.h, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
=> Fix rust::Fn call with non-const reference argument

macro/src/expand.rs, src/lib.rs
This warning is mostly equivalent to `improper_ctypes` but applies to function definitions as opposed to declarations.
```rust
extern "C" {
// improper_ctypes
pub fn c(_s: &str);
}
// improper_ctypes_definitions
pub extern "C" fn r(_s: &str) {}
```
```console
warning: `extern` block uses type `str`, which is not FFI-safe
--> src/lib.rs:3:18
|
3 |     pub fn c(_s: &str);
|                  ^^^^ not FFI-safe
|
= note: `#[warn(improper_ctypes)]` on by default
= help: consider using `*const u8` and a length instead
= note: string slices have no C equivalent
warning: `extern` fn uses type `str`, which is not FFI-safe
--> src/lib.rs:7:25
|
7 | pub extern "C" fn r(_s: &str) {}
|                         ^^^^ not FFI-safe
|
= note: `#[warn(improper_ctypes_definitions)]` on by default
= help: …
```
=> Deny improper_ctypes_definitions in generated code

macro/src/expand.rs, tests/ffi/lib.rs, tests/test.rs
=> Fix undeclared lifetime when fn ptr arg contains outer lifetime

syntax/attrs.rs
Fixes #833.
Example:
```rust
#[cxx::bridge]
mod ffi {
#![deny(missing_docs)]
include!("example/include/header.h");
/// wow
fn f();
}
}
pub use self::ffi::*;
```
=> Support inner attributes inside bridge

src/rust_string.rs, src/rust_vec.rs
This restores the `Drop` behavior prior to #821 for both types. I don't think either of these drops is ever currently invoked, because we only ever manipulate `RustString` / `RustVec` by value from Rust in one of the following forms, neither of which involves running Drop. However this change is likely to prevent future confusion as we extend the API of these types.
```rust
// fn() -> Vec<T>
#[export_name = "..."]
unsafe extern "C" fn __r_return_rust_vec(__return: *mut ::cxx::private::RustVec<u8>) {
fn __r_return_rust_vec() -> ::std::vec::Vec<u8> {...}
::cxx::private::catch_unwind(__fn, move || {
::std::ptr::write(
__return,
::cxx::private::RustVec::from(__r_return_rust_vec()),
)
})
}
```
```rust
// fn(Vec<T>)
#[export_name = "..."]
unsafe extern "C" fn __r_take_rust_vec(v: *mut …
```
=> Add impls for dropping RustString/RustVec ffi wrappers

macro/src/expand.rs, src/function.rs
Part of #744.
Without this, it's possible for the macro-expanded code to trigger improper_ctypes lints.
```console
error: `extern` block uses type `()`, which is not FFI-safe
--> tests/ffi/lib.rs:2577:44
|
2577 |             fn __c_take_callback(callback: ::cxx::private::FatFunction);
|                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
|
note: the lint level is defined here
--> tests/ffi/lib.rs:1439:8
|
1439 | #[deny(improper_ctypes, improper_ctypes_definitions)]
|        ^^^^^^^^^^^^^^^
= help: consider using a struct instead
= note: tuples have unspecified layout
```
=> Make FatFunction private contents into proper ctype

gen/src/write.rs, macro/src/expand.rs, src/cxx.cc, src/cxx_vector.rs, tests/ffi/tests.cc, tests/test.rs
Closes #838 (originally #778).
=> Add CxxVector::pop in Rust

src/cxx_string.rs, src/exception.rs, src/extern_type.rs, src/function.rs, src/lib.rs, src/opaque.rs, src/result.rs, src/rust_slice.rs, src/rust_str.rs, src/rust_string.rs, src/rust_type.rs, src/rust_vec.rs, src/unwind.rs, src/weak_ptr.rs
To help flag missing documentation on publicly accessible APIs.
=> deny(missing_docs) at crate root

macro/src/expand.rs
The `clippy::upper_case_acronyms` lint is newly introduced in the Clippy that shipped with rustc 1.51.0. When building CXX-generated Rust code with a toolchain older than 1.51.0, this PR avoids a `clippy::unknown_clippy_lints` warning in the generated code.
```console
warning: unknown clippy lint: clippy::upper_case_acronyms
--> path/to/bridge.rs:7:1
|
7 | #[cxx::bridge]
| ^^^^^^^^^^^^^^
|
= note: `#[warn(clippy::unknown_clippy_lints)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unknown_clippy_lints
= note: this warning originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
=> Avoid warning on unknown upper_case_acronyms lint on old clippys

gen/build/Cargo.toml, gen/cmd/Cargo.toml, gen/lib/Cargo.toml, gen/src/write.rs, macro/Cargo.toml, macro/src/clang.rs, macro/src/expand.rs, macro/src/lib.rs, syntax/attrs.rs, syntax/check.rs, syntax/discriminant.rs, syntax/file.rs, syntax/mod.rs, syntax/names.rs, syntax/parse.rs, syntax/tokens.rs, syntax/types.rs, third-party/BUCK, third-party/BUILD, third-party/Cargo.lock
This PR adds an optional feature based on https://github.com/dtolnay/clang-ast to extract information about shared enums (variant names, discriminant values, repr type) from a serialized Clang AST of the associated C++ headers.
The user-facing change is:
```diff
#[cxx::bridge]
mod ffi {
extern "C++" {
include!("path/to/ServiceManager.h");
}
...
-     #[repr(i32)]
enum ServiceState {
-         DISABLED = 0,
-         ENABLED = 1,
-         PRODUCTION = 2,
-         QA_SERVICE = 4,
-         IN_REPAIR = 8,
+         #![variants_from_header]
}
}
```
Wiring up an AST dump in a Buck-based build looks something like:
```python
def rust_library(
name,
env = {},
cxx_bridge = None,
cxx_deps = None,
**kwargs):
if cxx_bridge:
rust_cxx_bridge(
name = "%s@bridge" % name,
src = cxx_bridge,
deps = …
```
=> Experimental support for enum variant names and discriminant values retrieved from C++

macro/Cargo.toml, macro/src/clang.rs, third-party/Cargo.lock
Ditto #851, these files get fairly large -- but compress very well.
=> Support gz compressed AST input

macro/src/expand.rs, src/cxx_vector.rs, tests/ffi/lib.rs, tests/ui/vector_autotraits.stderr
=> Fix "not FFI-safe" on CxxVector containing struct containing Rust string

book/src/build/cmake.md
Added an additional example on how to integrate cxx with a cmake project, this utilizing Corrosion.
=> add additional cmake example

WORKSPACE, tools/bazel/vendor.bzl
Background:
tools/bazel/vendor is just running 'cargo', hoping to find it somewhere
in $PATH.
Problem:
rules_rust try to be hermetic, and not use the cargo of the system, but
the cargo of the toolchain installed.
This means that if the cargo on the system is different from the cargo
used by cxx.rs, or the system does not have a cargo at all, bad things
will happen when using cxx.rs.
In this change:
use the recommended way to find/install the tool. Thanks to Andre in the
=> bazel: don't use cargo in $PATH, make the build hermetic.

syntax/check.rs, syntax/trivial.rs, tests/ui/slice_of_type_alias.rs, tests/ui/slice_of_type_alias.stderr, tests/ui/slice_unsupported.stderr
```rust
// ffi.rs
use cxx::{type_id, ExternType};
#[repr(C)]
struct ElementTrivial(usize);
#[cxx::bridge]
mod ffi {
type ElementTrivial = crate::ElementTrivial;
fn f(slice: &mut [ElementTrivial]);
}
}
unsafe impl ExternType for ElementTrivial {
type Id = type_id!("ElementTrivial");
type Kind = cxx::kind::Trivial;
}
```
```cpp
// thing.h
#include "rust/cxx.h"
struct ElementTrivial;
void f(rust::Slice<const ElementTrivial> slice);
```
=> Support slice of trivial extern type alias

include/cxx.h, src/cxx.cc, src/symbols/rust_string.rs, tests/ffi/tests.cc
This patch exposes String::from_utf16 to the C++ interface for rust::String.
=> Add UTF-16 rust::String initialization

macro/src/expand.rs, tests/ui/array_len_suffix.stderr, tests/ui/expected_named.stderr, tests/ui/result_no_display.stderr, tests/ui/unsupported_elided.stderr
Updates the span of the tokens around `impl ::std::fmt::Display` in the expansion of fallible extern Rust functions to account for some diagnostic changes from https://github.com/rust-lang/rust/pull/86532.
=> Update ui test suite to nightly-2021-08-12

src/cxx.cc, src/cxx_string.rs
Removes all characters from the string.
Matches the behavior of C++ [std::string::clear](https://en.cppreference.com/w/cpp/string/basic_string/clear).
Note: **unlike** the guarantee of Rust's `std::string::String::clear`, the C++ standard does not require that capacity is unchanged by this operation. In practice existing implementations do not change the capacity but all pointers, references, and iterators into the string contents are nevertheless invalidated.
=> Add CxxString::clear method

third-party/BUILD, tools/bazel/rust.bzl
This uses the `cargo_build_script` rule introduced by https://github.com/bazelbuild/rules_rust/pull/320.
=> Bazel: build and execute proc-macro2 build script

.github/workflows/ci.yml, gen/build/src/lib.rs, gen/cmd/src/main.rs, gen/lib/src/lib.rs, macro/src/derive.rs, macro/src/lib.rs
The Clippy crash that caused us to disable it (https://github.com/rust-lang/rust-clippy/issues/7423) was fixed in https://github.com/rust-lang/rust-clippy/pull/7428 + https://github.com/rust-lang/rust/pull/87152 in nightly-2021-07-16.
=> Re-enable clippy after upstream crash fix

syntax/attrs.rs, syntax/doc.rs
=> Pass through doc(hidden) attribute

gen/src/write.rs
Previously these did not respect
`cxxbridge --cxx-impl-annotations`
and similar directives in other build pipelines. These may be linked against
from Rust code just as other generated functions are, so it's important that
they are exported from shared objects in a similar fashion.
Fixes #966.
=> Export UniquePtr and similar functions.

syntax/attrs.rs
#941 added support for `derive(Serialize)` and `derive(Deserialize)` on data structures inside the cxx::bridge module, but previously the use of a `serde(...)` inert attribute would still fail to compile:
```rust
#[cxx::bridge]
mod ffi {
#[derive(Serialize)]
struct BlobMetadata {
#[serde(rename = "len")]
size: usize,
tags: Vec<String>,
}
...
}
```
```console
error: unsupported attribute
--> src/main.rs:6:9
|
6 |         #[serde(rename = "len")]
|         ^^^^^^^^^^^^^^^^^^^^^^^^
```
This PR accepts and preserves those `serde(...)` attributes so that they can be read by Serde's derives.
=> Pass through serde attributes

src/lib.rs
On edition 2018+, `use std::…` implies an implicit `extern crate std`, even inside of a `#[no_std]` crate. This PR prevents this std dependency being inserted inadvertently.
Part of #933.
=> Block inadvertent use of items from libstd in no_std mode

book/src/binding/vec.md, gen/src/write.rs, include/cxx.h, macro/src/expand.rs, src/cxx.cc, src/rust_vec.rs, src/symbols/rust_vec.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
Added a `clear` method to rust::Vec to address https://github.com/dtolnay/cxx/issues/950.
Closes #950.
=> Add Vec clear

macro/src/expand.rs, src/lib.rs, src/unwind.rs
This describes its purpose in the context of cxx better. We are blocking the unwind from propagating across the extern "C" signature by aborting, not continuing the program like in the case of std::panic::catch_unwind.
=> Rename catch_unwind -> prevent_unwind

Cargo.toml, src/cxx_string.rs, src/exception.rs, src/extern_type.rs, src/lib.rs
=> Mark feature-gated APIs in rendered rustdoc

macro/src/derive.rs, macro/src/expand.rs, macro/src/generics.rs, tests/ui/deny_elided_lifetimes.rs, tests/ui/deny_elided_lifetimes.stderr
Closes #907.
This ensures compatibility with `-D elided-lifetimes-in-paths` / `deny(elided_lifetimes_in_paths)`. While I am not a fan of this opt-in lint and I don't think codebases should use it, that should ultimately be up to them and it's not too hard for us to support.
=> Fill in elided lifetimes in generated code

book/src/tutorial.md
I was running through the tutorial today, and found that when I tried to run my code at the end of the [calling a rust function from C++ example](https://cxx.rs/tutorial.html#calling-a-rust-function-from-c), I was met with the following errors.
```
-*- mode: compilation; default-directory: "~/Dev/cxx-demo/" -*-
Compilation started at Mon Jun 14 23:52:53
cargo run
Compiling cxx-demo v0.1.0 (/Users/brendond/Dev/cxx-demo)
The following warnings were emitted during compilation:
warning: src/blobstore.cc:12:15: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
warning:   std::string contents;
warning:               ^
warning: /Applications/Xcode_11.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xcto …
```
=> Add cxx include directive to blobstore header in middle example

book/src/binding/vec.md, gen/src/write.rs, include/cxx.h, macro/src/expand.rs, src/cxx.cc, src/rust_vec.rs, src/symbols/rust_vec.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
Based on the model of #951, which added `Vec<T>::clear`. The `truncate`
method is the more general form of clear.
(If we wanted to, we could delete the binding for `clear` and implement
`clear` as a call to `truncate(0)` on the C++ side, but seemed worth
leaving in in case the Rust `clear` implementation one day gets
smarter.)
=> Add Vec<T>::truncate to C++ API

book/src/binding/string.md, include/cxx.h, src/cxx.cc, src/symbols/rust_string.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
This constructor maps to `String::from_utf8_lossy` or
`String::from_utf16_lossy`. It's useful in situations where producing a
slightly garbled string on invalid Unicode data is preferable to
crashing the process, e.g. when passing error messages from C++ to Rust.
=> Add String::lossy constructors to C++ API

src/cxx.cc
This would catch UB of the kind called out in https://github.com/dtolnay/cxx/pull/984#discussion_r775417432.
As far as I can tell from https://groups.google.com/g/llvm-dev/c/eJRto1ipCYQ, the behavior of even constructing any insufficiently aligned ptr in C++ is unspecified by the standard, but may be implementation defined. I don't know if that is leveraged by compilers in practice or if enough real-world C++ code is broken that implementations just treat these pointers like integers. On implementations that view insufficient alignment as UB the assertions added here would just do nothing, which is fine.
=> Assert that incoming char16_t* are sufficiently aligned

gen/src/nested.rs, macro/src/expand.rs, syntax/attrs.rs, syntax/cfg.rs, syntax/impls.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs
=> Store parsed cfg attributes into syntax tree

gen/src/cfg.rs, gen/src/mod.rs
Needed for #989. There will be different implementations for the cxx-build crate (using `CARGO_CFG_…` environent variables set by Cargo for build scripts) and the cxxbridge-cmd crate (using `--cfg` flags) in upcoming PRs.
=> Add a trait for evaluating cfg expressions

gen/build/src/cargo.rs, gen/build/src/lib.rs
This wraps up #989 for Cargo-based builds. Non-Cargo builds are going to need a different cfg evaluator for the cxxbridge-cmd crate in a later PR.
=> Add a cfg evaluator for the cxx-build crate

gen/cmd/src/app.rs, gen/cmd/src/cfg.rs, gen/cmd/src/main.rs, gen/cmd/src/test.rs
Conditional compilation support for non-Cargo builds (part of #989). This is the non-Cargo followup to #1000. The C++ code generator evaluates `#[cfg(...)]` attributes by taking flags equivalent to `rustc`'s `--cfg` flag:
```console
$ cxxbridge --cfg 'unix' --cfg 'target_arch="x86_64"' --cfg 'target_endian="little"' --cfg 'test=false' …
```
=> Add a cfg evaluator for the non-Cargo builds

gen/build/src/cargo.rs
`cfg(test)` can't work in Cargo builds because Cargo will make two rustc invocations to build your crate in library mode and test mode, but runs the build script only once across the two of those. We need to pick either true or false for that cfg on the C++ side.
=> Disallow cfg(test) inside Cargo builds

gen/src/cfg.rs
For example in `#[cfg(any(target_os = "android", unix))]`, if we know `--cfg unix=true`, the value of this cfg is known even if `target_os` is not known. Previously this would fail on the `target_os` without looking at `unix`.
=> Support all/any cfg evaluation with not all clauses determinate

gen/cmd/Cargo.toml, gen/cmd/src/app.rs, third-party/BUCK, third-party/BUILD, third-party/Cargo.lock
There are several deprecations in this release:
https://github.com/clap-rs/clap/releases/tag/v3.1.0
=> Update to clap 3.1.0

.bazelrc
macOS C++ toolchains from Apple do not contain lld, so bazel builds in
this repo would fail. This change scopes this only to Linux
=> [bazel] Only use lld on Linux

BUILD, WORKSPACE, demo/BUILD, tests/BUILD, third-party/BUILD, tools/bazel/third_party.bzl
=> Enforce edition on all Bazel targets

WORKSPACE
Closes #1031. Closes #1032.
Requires https://github.com/bazelbuild/rules_rust/pull/1254, since some targets from the rules_rust repo otherwise end up using the default edition set by cxx's WORKSPACE. (This behavior is silly, but a consequence of https://github.com/bazelbuild/rules_rust/issues/1251.)
Using rules_rust's current `main` branch this change would fail as follows:
```console
$ bazel build ...
INFO: Analyzed 48 targets (5 packages loaded, 382 targets configured).
INFO: Found 48 targets...
ERROR: /home/david/.cache/bazel/_bazel_david/ebce1d0721fb68dda9c70c0dd1405803/external/rules_rust/util/process_wrapper/BUILD.bazel:6:36: Compiling Rust (without process_wrapper) bin process_wrapper (4 files) [for host] failed: (Exit 1): rustc failed: error executing command …
```
=> Set up Bazel rust_repositories with a default edition that is not usable

tools/bazel/vendor.bzl
Adds support to vendor.bzl for resolving the arm triplet. This only works with Bazel 5.1, but the way we access the new field should be safe for older versions and result in a negative check, maintaining the old behavior
=> support resolving arm triplet with bazel

tools/bazel/vendor.bzl
The previous check was wrong, seems like Bazel puts aarch64 as the architecture for both Linux and macos. Verified this on both platforms
=> bazel: fix arm check

WORKSPACE, tools/bazel/third_party.bzl
https://github.com/bazelbuild/rules_rust/pull/1257 + https://github.com/bazelbuild/rules_rust/pull/1256
=> Pull in my landed edition-related PRs from Bazel rules_rust

WORKSPACE
This function is documented as deprecated in rules_rust.
```markdown
**Deprecated**: Use [rules_rust_dependencies](#rules_rust_dependencies)
and [rust_register_toolchains](#rust_register_toolchains) directly.
```
=> Replace deprecated rust_repositories call in bazel WORKSPACE

WORKSPACE, tools/bazel/vendor.bzl
In https://github.com/bazelbuild/rules_rust/pull/1289 I implemented a better way to figure out the right triple to use with `load_arbitrary_tool`.
This replaces the incomplete `if`/`elif`/`else` logic from #893 and #1038 and #1039.
=> Replace half-baked repository_os logic with get_host_triple

macro/src/expand.rs, syntax/attrs.rs, syntax/parse.rs
=> Clippy attrs on extern "Rust" blocks

macro/src/expand.rs
when use cxx with derive macros with helper container attribute will meet the warning
https://github.com/rust-lang/rust/issues/79202
a minimal case:
```
#[cxx::bridge]
mod ffi {
#[derive(Debug, Default, Deserialize)]
#[serde(rename(deserialize = "de_name"))]
struct Data {
size: usize,
}
}
```
=> make #derive before #attr when expand to avoid warning legacy_derive_helpers

book/src/build/cmake.md
I always wished for an inverted example when learning to use CXX (blobstore in Rust, main() in C++).
I decided to make it, and to keep it as close to the official demo as possible. I also kept the CMake-configuration to a minimum, avoiding advanced topics & tricks, since it's supposed to be an introductory example.
Tested on Linux, Mac, Windows.
=> Added another CMake example application

gen/build/src/out.rs, gen/src/fs.rs
=> Fix cxx-build on Windows when `target` dir is populated from a cache with dangling symlinks

book/src/build/cmake.md
Update the CMake docs repositories list with the `geekbrother/cxx-corrosion-cmake` repository that has good examples, is easy to build with Docker and Nix, and a modern CMake file to use a CXX+Corrosion.
=> [docs] Add `geekbrother/cxx-corrosion-cmake` repo to the CMake docs.

src/unique_ptr.rs
Similar to a std::boxed::Box, a UniquePtr itself can be Unpin, even if
its target is not Unpin.
As UniquePtr is not a self-referential type, this is safe to do.
See:
- https://doc.rust-lang.org/std/pin/index.html#unpin
- https://doc.rust-lang.org/std/boxed/struct.Box.html#impl-Unpin
=> Add Unpin impl for UniquePtr.

book/src/binding/cxxstring.md
The previous code works in _some_ STL implementations, namely if _either_ of the following is true:
1. At least one of the other four STL headers included by json.h transitively includes \<string\>, as opposed to just \<stringfwd.h\>; or
2. The way std::variant is implemented does not require knowing the inner types' type traits when just naming the std::variant without yet instantiating any of its member function templates.
On other STL implementations in which neither of the above is true, this example failed to build with an error such as:
```console
In file included from target/debug/build/example-d2d484e0c793273c/out/cxxbridge/sources/example/src/main.rs.cc:1:
In file included from target/debug/build/example-d2d484e0c793273c/out/cxxbridge/crate/example/include/json.h:2:
In file …
```
=> Fix missing <string> include in std::string example

gen/src/write.rs
=> Allow Rust vector of array of trivially relocatable type

gen/cmd/Cargo.toml, gen/cmd/src/app.rs, gen/cmd/src/test.rs, third-party/BUCK, third-party/BUILD, third-party/Cargo.lock
Release announcement: https://epage.github.io/blog/2022/09/clap4/
=> Update argument parser to clap 4

gen/build/Cargo.toml
`codespan-reporting` 0.11.0 does not build with `-Zminimal-versions` because it has a constraint
on `termcolor = 1` whereas it depends on the `Copy` trait being implemented on types in `termcolor`
which were not added until 1.0.4.
See:
- https://github.com/brendanzab/codespan/issues/322
- https://github.com/brendanzab/codespan/commit/e99c867339a877731437e7ee6a903a3d03b5439e
=> Update codespan-reporting to build with -Zminimal-versions

gen/src/builtin.rs, gen/src/write.rs, src/cxx.cc
This unblocks adding an overload of `operator()` so that `fail` can be called with a `std::string`, not just a `const char *`, and can skip the strlen computation in that case.
=> Factor out the Fail lambda from all trycatch calls

src/cxx.cc, src/result.rs, src/symbols/exception.rs
Previously we'd create a PtrLen with the C++ string's length and the String::from_utf8_lossy string's data pointer. This is later turned back into a Rust string by:
https://github.com/dtolnay/cxx/blob/a39652409c2838138abc7e2eb88e5af095b632ce/src/result.rs#L61-L66
Since in general the length of string produced by from_utf8_lossy can be longer than the original string, this could end up truncating characters off the end of the exception message when printed from Rust code.
=> Fix incorrect string len if an exception's message is invalid UTF-8

gen/src/builtin.rs, src/cxx.cc
**Before:**
```cpp
template <typename Try, typename Fail>
static void trycatch(Try &&func, Fail &&fail) noexcept try {
func();
} catch (const whatever &ex) {
std::ostringstream buf;
ex.dump(buf);
fail(buf.str().c_str());
}
```
**After:** just `fail(buf.str())` without `.c_str()`, and performs better because we bypass a redundant strlen computation.
=> Allow trycatch to call Fail using std::string

gen/src/builtin.rs, gen/src/write.rs
=> Adopt east const in generated code to avoid ambiguities

.github/workflows/ci.yml, third-party/Cargo.lock, third-party/Cargo.toml, tools/bazel/vendor.bzl
**Before:**
```
adler-1.0.2                  libc-0.2.137            serde_json-1.0.89
bitflags-1.3.2               link-cplusplus-1.0.7    strsim-0.10.0
cc-1.0.77                    memmap-0.7.0            syn-1.0.105
cfg-if-1.0.0                 miniz_oxide-0.6.2       termcolor-1.1.3
clang-ast-0.1.9              once_cell-1.16.0        toml-0.5.9
clap-4.0.29                  os_str_bytes-6.4.1      trybuild-1.0.72
clap_lex-0.3.0               pkg-config-0.3.26       unicode-ident-1.0.5
codespan-reporting-0.11.1    proc-macro2-1.0.47      unicode-width-0.1.10
crc32fast-1.3.2              quote-1.0.21            winapi-0.3.9
dissimilar-1.0.4             rustversion-1.0.9       winapi-i686-pc-windows-gnu-0.4.0
flate2-1.0.25                ryu-1.0.11              winapi-util-0.1.5 …
```
=> Reduce the set of crates that get vendored

.github/workflows/ci.yml, WORKSPACE
At some point around the middle of this year, https://github.com/bazelbuild/rules_rust started getting regular releases published. Before that, we'd only been using it via git commits on its `master` (later `main`) branch for 2+ years.
=> Update to use released version of Bazel rules_rust

tests/ffi/build.rs
Previously, modifying tests.h/cc would not trigger rebuild of the bridge, preventing efficient test development.
=> Fix: pick up changed tests.h/cc to rebuild the bridge

src/cxx_string.rs, tests/cxx_string.rs
This allows formatted writes (e.g. with the `write!()` macro) directly on a `CxxString`. This can eliminate a needless allocation from formatting to a `String` then converting to a `CxxString`.
While testing this, I ran into #1201. Nothing else stood out as unusual.
=> Implement fmt::Write for CxxString

.github/workflows/ci.yml, third-party/BUCK, third-party/reindeer.toml
This eliminates the `cargo vendor` and `reindeer` step. Users can checkout the repo and immediately run `buck2 build`.
<pre>
$ <b>git clone https://github.com/dtolnay/cxx</b>
$ <b>cd cxx</b>
$ <b>git submodule update --init</b>
<strike>$ cargo vendor --versioned-dirs --locked --manifest-path third-party/Cargo.toml third-party/vendor</strike>
<strike>$ reindeer --third-party-dir third-party buckify</strike>
$ <b>buck2 build ...</b>
</pre>
=> Use http_archive for buck crates without vendoring

gen/lib/src/error.rs
The Error type exposed in cxx-gen is very minimal currently. For use in CXX-Qt, we'd like to access the span if the Error has one. This would allow us to greatly improve our build script diagnostics (very similar to how CXX displays errors itself).
cc: @ahayzen-kdab
See: https://github.com/KDAB/cxx-qt/issues/536
=> cxx-gen: Add span() to Error type

src/cxx.cc
This is a suggested fix for #1225.
=> Explicit cast from std::size_t to std::streamsize in cxx.cc

include/cxx.h
This is a suggested fix for #1227. I was able to build both the `cxx` crate dependency and my own C++ code referencing generated `cxxbridge` headers with this change without disabling the signed/unsigned mismatch warning in MSVC.
=> Explicit cast from size_t to Slice<T>::iterator::difference_type in cxx.h

src/cxx.cc
The usage of std::cerr significantly increases binary size. However, many people disable exceptions for binary size. Also, std::terminate also uses std::cerr to print an abort message and then abort. Here we manually print the abort message and thus use std::abort instead.
Fix #1239
=> Remove usage of std::cerr

.bazelrc, demo/BUILD
Fixes #1254.
The choice of `-std=c++17` matches what we have been setting up for Buck builds.
https://github.com/dtolnay/cxx/blob/377f47e5a4519784083cc6ab39f24ec73f357cf7/tools/buck/toolchains/BUCK#L6-L12
=> Globally set C++ standard in Bazel builds

Cargo.toml
Adapted from the "@using_cxx" example added by https://github.com/bazelbuild/rules_rust/pull/2103.
I plan to send a rules_rust PR to read this package metadata and obviate the `annotations = { "cxx": [crate.annotation( .... )] }` for crates that provide it.
I considered a more TOML-native form for `additive_build_file_content`, but just using multiline string literal containing Starlark seems all right. Support for the structured form can be introduced separately.
```toml
[package.metadata.bazel]
extra_aliased_targets = { cxx_cc = "cxx_cc" }
gen_build_script = false
[[package.metadata.bazel.additive_build_file_content]]
[package.metadata.bazel.additive_build_file_content.cc_library]
name = "cxx_cc"
srcs = ["src/cxx.cc"]
hdrs = ["include/cxx.h"]
include_prefix = "rust"
includes = …
```
=> Add bazel annotations as Cargo.toml package metadata

gen/src/write.rs, macro/src/expand.rs, src/cxx.cc, src/cxx_vector.rs, tests/cxx_vector.rs
When constructing a CxxVector to pass to C++, you have to end up writing your own utility function that constructs a `UniquePtr<CxxVector<...>>` and add that to your projects cxx bridge. Creating an empty vector seems like a simple enough task to afford having an API for it on `CxxVector`.
=> Add CxxVector::new for creating an empty vector

src/cxx_vector.rs, src/macros/concat.rs, src/macros/mod.rs, src/shared_ptr.rs, src/symbols/rust_vec.rs, src/weak_ptr.rs
This workaround was originally necessary as the `#[attribute = concat!(...)]` was not accepted by rustc's parser. It became supported in Rust 1.54 (https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html#attributes-can-invoke-function-like-macros).
Since fe16a5dea3a3f2995cf41316c88f2c8961f8f3e7, Rust 1.60+ is required by cxx, so `concat!` can be used directly in an attribute without workaround.
=> Remove 'attr!' wrapper around concat in link_name & export_name attributes

build.rs
Bazel by default builds in $CARGO_MANIFEST_DIR, but can be instructed to build elsewhere (e.g. so that toolchains which involve relative paths can use correct relative paths).
This allows that to function.
=> Use full path relative to $CARGO_MANIFEST_DIR when compiling

Cargo.toml
Context: https://github.com/dtolnay/cxx/pull/1257#issuecomment-1755782014, https://github.com/bazelbuild/rules_rust/pull/2192
=> bazel: Add dependency on cxx_cc via annotation

macro/src/expand.rs, tests/ffi/lib.rs
=> Make compatible with deny(unsafe_op_in_unsafe_fn)

gen/build/src/lib.rs, gen/cmd/src/main.rs, gen/lib/src/lib.rs, macro/src/lib.rs
This lint got downgraded from `pedantic` to `nursery` by https://github.com/rust-lang/rust-clippy/pull/7568 so we no longer run it.
=> Remove option_if_let_else clippy suppression

src/lib.rs
This regressed with https://github.com/rust-lang/rust/pull/113091 in nightly-2023-12-16. The doc(cfg()) from the type definition is no longer rendered.
=> Restore documented cfg on cxx::Exception

book/src/tutorial.md
I ran into some compilation issues while going through the tutorial step-by-step.
Looking at the tutorial files in the repo, I expect this was caused by me missing the `cargo:rerun-if-changed` lines in the build script (without them, changes to the .cc and .h files did not have any effect).
I'm adding those on the tutorial page so other people will be aware of them from the start.
=> Include printing of "cargo:rerun-if-changed" in tutorial

src/lib.rs, syntax/cfg.rs, syntax/mod.rs, tests/ffi/lib.rs
Warnings are new in nightly-2024-01-06 due to https://github.com/rust-lang/rust/pull/118297.
=> Work around new dead_code warnings

gen/src/mod.rs
This is obsolete since `proc_macro2::is_available()` became available in Rust 1.57, which avoids needing a catch_unwind for libproc_macro detection.
=> Remove pre-1.57 proc_macro2::fallback::force()

gen/src/write.rs
If there are other structs in `toposorted_structs` before `strct`, they were written with the methods of `strct` instead of their own. This commit fixes that.
This commit also fixes the check against `out.types.cxx` that should prevent duplicate definitions. I didn't encounter any such issues, but I still think that it makes sense to fix it.
Both issues were introduced in commit 5439fa195bbece443d261d40bf08d77012d44e58.
<strong>I encountered this issue with the following bridge module:</strong>
<details>
```rust
#[cxx::bridge]
mod ffi {
// [...]
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[namespace = "sensor_msgs"]
#[cxx_name = NavSatFix]
pub struct sensor_msgs__NavSatFix {
pub header: std_msgs__Header,
pub status: sensor_msgs__NavSatStatus, …
```
=> Fix: Use correct methods when writing toposorted structs

README.md, book/src/build/cargo.md, book/src/tutorial.md
Small documentation update after running into this issue using the MSVC `cl` compiler on Windows.
Thanks for the awesome library.
---
The `-std=c++11` flag only works with GNU-style compiler frontends for MSVC this should be `/std:c++11`.
Even better is to use the builder's explicit C/C++ standard setter.
=> Documentation: Use `builder.std` rather than explicit compiler flags

Cargo.toml, build.rs, flags/src/impl.rs, flags/src/lib.rs, gen/build/Cargo.toml, tests/ffi/build.rs, third-party/Cargo.toml
Based on https://github.com/dtolnay/cxx/pull/1321.
I am not certain whether this is better. For example, would this change be problematic if someone has been using a C++ compiler that does not support `-std=c++20`, but had enabled our `"cxx/c++20"` Cargo feature, yet was not using any C++20 features in their headers? It would have silently worked before by noop-ing the `flag_if_supported`, but maybe it shouldn't have.
=> Set C++ standard version using cc::Build::std

.github/workflows/ci.yml, build.rs, src/c_char.rs
`core::ffi::c_char` became available in Rust 1.64.0.
<https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#stabilized-apis>
=> Use libcore's c_char if available

MODULE.bazel, MODULE.bazel.lock, third-party/BUILD, tools/bazel/extension.bzl
In this approach, repos for the vendored crates.io libraries are no longer direct dependencies of the root module. Instead there is a single direct dependency `@vendor` through which we can access the other repos.
=> Bazel: switch to trampoline repo

gen/lib/src/lib.rs, gen/src/mod.rs
This allows for users of cxx_gen to choose a cfg_evaluator, otherwise they cannot have cfg attributes in bridges.
=> gen: allow for cfg_evaluator to be set in cxx_gen

build.rs, tests/ffi/build.rs, tools/cargo/build.rs
Context: https://blog.rust-lang.org/2024/05/06/check-cfg.html
=> Resolve unexpected_cfgs warning

.buckconfig, .github/workflows/buck2.yml, .gitmodules
https://buck2.build/docs/users/advanced/external_cells/
=> Switch to bundled buck2 prelude

Cargo.toml, build.rs, src/cxx_string.rs, src/exception.rs, src/extern_type.rs, src/lib.rs
As of recently, docs.rs defines a `docsrs` configuration for all builds, so we no longer need to do it using our own `package.metadata.docs.rs.rustdoc-args`.
=> Rely on docs.rs to define --cfg=docsrs by default

src/cxx.cc
On illumos at least you have `std::is_same<char, int8_t> = true` which means a whole bunch of duplicate definition errors.
=> Give char the if_unique treatment too to handle possible collisions with [u]int8_t definitions.

include/cxx.h, tests/ffi/tests.cc
After this commit, it is possible to explicitly construct `rust::Slice` from a reference to any continguous C++ container (any container that exposes `data` and `size` accessors).
The new constructor results in a slightly more ergonomic code, by removing the need to explicit extract and pass `c.data()` and `c.size()` at a callsite of a `rust::Slice` constructor.  The callsites using the new constructor are also more obviously correct, because they doesn't require double-checking that the passed `data` and `size` match.
The implementation of the new constructor mimics `std::span` from C++20, but for C++11 compatibility reimplements `std::size` / `std::ranges::size` in a pedestrian way (same for `std::data` / `std::ranges::data`).
=> Ergonomics: allow constructing `rust::Slice` from any C++ container.

src/unique_ptr.rs
This commit implements forwarding of `Read` trait implementation from `UniquePtr<T>` to the pointee type.  This is quite similar to how `Box<T>` also forwards - see
https://doc.rust-lang.org/std/boxed/struct.Box.html#impl-Read-for-Box%3CR%3E
Just as with `Box<T>`, the `impl` cannot be provided in the crate introducing `T`, because this violates the orphan rule.  This means that before this commit a wrapper newtype would be required to work around the orphan rule - e.g.:
```
struct UniquePtrOfReadTrait(cxx::UniquePtr<ffi::ReadTrait>);
impl Read for UniquePtrOfReadTrait { … }
```
After this commit, one can provide an `impl` that works more directly with the C++ type `T` (the FFI will typically require passing `self: Pin<&mut ffi::ReadTrait>`):
```
impl<'a> Read for Pin<&'a mut …
```
=> `impl<T> Read for UniquePtr<T> where ... Pin<&a mut T> : Read`.

src/opaque.rs, tests/ui/opaque_autotraits.stderr
@capickett noticed that passing a cxx-generated opaque C++ type by reference gets annotated with an unwanted, incorrect `readonly` attribute. We have observed miscompiles that arise from this in real-world code when using cross-language ThinLTO.
According to https://llvm.org/docs/LangRef.html:
> **readonly**
>
> This attribute indicates that the function does not write through this pointer argument, even though it may write to the memory that the pointer points to.
>
> If a function writes to a readonly pointer argument, the behavior is undefined.
For the following repro:
```rust
#[no_mangle]
pub fn repro(opaque: &cxx::private::Opaque) {
extern "C" {
fn do_repro(opaque: *const cxx::private::Opaque);
}
unsafe { do_repro(opaque) }
}
```
this is the LLVM IR generated before this PR:
```llvm …
```
=> Drop "readonly" LLVM attribute from references to opaque C++ types

src/opaque.rs, tests/test.rs
Opaque C++ types used to be automatically RefUnwindSafe prior to #1370, which is a fine default. This PR fixes a regression that manifests like this:
```console
error[E0277]: the type `UnsafeCell<PhantomData<()>>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
--> tests/test.rs:389:61
|
389 |     let _ref_unwind_safe = |c: &ffi::C| panic::catch_unwind(|| inspect(c));
|                                         ------------------- ^^^^^^^^^^^^^ `UnsafeCell<PhantomData<()>>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
|                                         |
|                                         required by a bound introduced by this call
|
= help: within …
```
=> Hide the UnsafeCell content of opaque C++ types in regard to unwind safety

gen/src/file.rs
=> Disregard module inner attrs during C++ codegen

third-party/Cargo.toml
Without this, `cargo update` generates a v4 lockfile by default, which is not supported by the `cargo-lock` crate that is used by `cargo-bazel`. It looks like v4 support has been implemented in https://github.com/rustsec/rustsec/pull/1206 but not released to crates.io.
For now, this workaround avoids the following error.
```console
$ bazel run //third-party:vendor
INFO: Analyzed target //third-party:vendor (363 packages loaded, 10315 targets configured).
INFO: Found 1 target...
Target //third-party:vendor up-to-date:
bazel-bin/third-party/vendor.sh
INFO: Elapsed time: 8.623s, Critical Path: 2.66s
INFO: 60 processes: 31 internal, 29 linux-sandbox.
INFO: Build completed successfully, 60 total actions
INFO: Running command line: bazel-bin/third-party/vendor.sh
Error: Failed to load lockfile: …
```
=> Work around outdated lockfile parser used by rules_rust

.github/workflows/ci.yml, Cargo.toml, README.md, build.rs, flags/Cargo.toml, gen/build/Cargo.toml, gen/lib/Cargo.toml, macro/Cargo.toml, src/lib.rs
Required for dropping a once_cell dependency in favor of standard library `std::sync::OnceLock` and `std::sync::LazyLock` in an upcoming PR.
=> Raise required compiler to Rust 1.70

MODULE.bazel
This fixed the error when using bazel build system for cxx as
https://github.com/dtolnay/cxx/blob/master/tools/bazel/rust_cxx_bridge.bzl#L3 using the `rules_cc`
```
ERROR: Skipping '//:cxx_helloworld': error loading package '': at /home/phongtran/.cache/bazel/_bazel_phongtran/2203687aa2e8f2dabc08191e61a17361/external/cxx.rs~/tools/bazel/rust_cxx_bridge.bzl:3:6: Unable to find package for @@[unknown repo 'rules_cc' requested from @@cxx.rs~]//cc:defs.bzl: The repository '@@[unknown repo 'rules_cc' requested from @@cxx.rs~]' could not be resolved: No repository visible as '@rules_cc' from repository '@@cxx.rs~'.
ERROR: error loading package '': at /home/phongtran/.cache/bazel/_bazel_phongtran/2203687aa2e8f2dabc08191e61a17361/external/cxx.rs~/tools/bazel/rust_cxx_bridge.bzl:3:6: Unable to …
```
=> Add rules_cc as bazel_dep

src/unique_ptr.rs
This commit implements forwarding of `Write` trait implementation from `UniquePtr<T>` to the pointee type.  This is quite similar to how `Box<T>` also forwards - see
https://doc.rust-lang.org/std/boxed/struct.Box.html#impl-Write-for-Box%3CW%3E
This commit has quite similar, orphan-rule-related motivation as the earlier https://github.com/dtolnay/cxx/pull/1368 which covered the `Read` trait.  For a more specific motivating example, please see http://review.skia.org/c/skia/+/923337/3/experimental/rust_png/ffi/FFI.rs#254
=> `impl<T> Write for UniquePtr<T> where ... Pin<&a mut T> : Write`.

Cargo.toml
This has the same effect as https://github.com/dtolnay/cxx/issues/1407#issuecomment-2509136343 and allows a tool like Corrosion to read a locked set of dependencies for cxxbridge-cmd out of any lockfile that contains cxx.
=> Disallow incompatible cxxbridge-cmd version appearing in the same lockfile

Cargo.toml
I don't think this makes any difference for generating a lockfile or Cargo feature unification or building anything, since the dependency is not enabled on any target platform. The only intended effect is cosmetically to move cxxbridge-cmd from "Dependencies" to "Build-Dependencies" in https://crates.io/crates/cxx/1.0.132/dependencies, as it is never something that would be built for the target platform, only the host platform.
=> Move cxxbridge-cmd from dependencies to build-dependencies

syntax/parse.rs, tests/ui/cxx_crate_name_qualified_cxx_string.rs, tests/ui/cxx_crate_name_qualified_cxx_string.stderr
One gotcha that sometimes trips new users of `cxx` is that `cxx::CxxString` works outside of `cxx::bridge`, but not within. 
This PR tries to improve this by providing a custom error message in this scenario.
Notes:
* I think that _any_ custom error message is a minor improvement over the status quo (with a generic "unsupported type" error message).  Additional improvements may be possible, but it's probably okay to do them incrementally later, in separate PRs.
- Feel free to tweak the error message as needed.  I wasn't sure if it's okay to call `cxx::` a "qualifier" but it seems okay (FWIW paths containing `::` are [called "qualified paths" in Rust reference](https://doc.rust-lang.org/reference/paths.html#qualified-paths)).
- Ideally the error message would also provide a hint (i.e. a …
=> Friendlier message when `cxx::CxxString` is used in a `#[cxx::bridge]`.

macro/src/expand.rs, tests/ffi/lib.rs, tests/ffi/module.rs, tests/ffi/tests.cc
Sometimes Rust functions declared inside the `#[cxx::bridge]` have to be marked as unsafe (e.g. if they need to use an explicit lifetime). When the actual, wrapped function is _not_ unsafe, then the generated code will result in an `unused_unsafe` warning.  For example:
```
Compiling cxx-test-suite v0.0.0 (/usr/local/google/home/lukasza/src/github/cxx/tests/ffi)
error: unnecessary `unsafe` block
--> tests/ffi/lib.rs:276:19
|
276 |         unsafe fn r_return_str_via_out_param<'a>(shared: &'a Shared, out_param: &mut &'a str);
|                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ unnecessary `unsafe` block
|
note: the lint level is defined here
--> tests/ffi/lib.rs:20:9
|
20  | #![deny(warnings)]  // Check that expansion of `cxx::bridge` doesn't trigger warnings.
|         ^^^^^^^^
= note: …
```
=> Suppress `unused_unsafe` warnings within the generated code.

tests/BUILD.bazel, tools/bazel/rust_cxx_bridge.bzl
This enables support for `visibility`, `testonly`, etc.
[1] https://bazel.build/reference/be/common-definitions#common-attributes
=> Add support for Bazel common attributes [1] in `rust_cxx_bridge`.

src/unique_ptr.rs, tests/test.rs
cxx accepts functions that take *mut T as an argument.
Such functions are of course used under odd niche circumstances;
it would be safer and better to take a &mut Pin<T>.
But in cases where such a function does exist, we'd most commonly
want to provide it a mutable pointer to a T which is safely
and uniquely owned by Rust, within a UniquePtr.
It was previously quite hard to do this:
```rust
let mut a = /* make UniquePtr to a thing */
unsafe { ffi::TakeA(std::pin::Pin::<&mut ffi::A>::into_inner_unchecked(a.pin_mut())) };
```
With this extra API, it becomes much more ergonomic:
```rust
let mut a = /* make UniquePtr to a thing */
unsafe { ffi::TakeA(a.as_mut_ptr()) }
```
Inspired by https://github.com/google/autocxx/issues/558
=> Add UniquePtr::as_mut_ptr

book/src/binding/slice.md, include/cxx.h
The main missing piece was that
https://en.cppreference.com/w/cpp/iterator/random_access_iterator requires that "`(a + n)` is equal to `(n + a)`", but `Slice::iterator` only supported `a + n` and didn't support `n + a`.
=> Tweak `rust::Slice` to become a C++20 `contiguous_range`.

book/src/binding/vec.md
rust::Vec uses the same iterators as rust::Slice, which changed in https://github.com/dtolnay/cxx/pull/1432.
https://github.com/dtolnay/cxx/blob/c6bb3b9996090777c081dfb3b4f3c58f739dcd4a/include/cxx.h#L356
https://github.com/dtolnay/cxx/blob/c6bb3b9996090777c081dfb3b4f3c58f739dcd4a/include/cxx.h#L360
=> Update iterator_category of Vec iterators in doc

book/src/binding/box.md, book/src/binding/result.md, book/src/binding/slice.md, book/src/binding/str.md, book/src/binding/string.md, book/src/binding/vec.md
Changes from https://github.com/dtolnay/cxx/pull/714.
=> Synchronize reference qualification of `operator=` to docs

.github/workflows/ci.yml, include/cxx.h, tests/ffi/tests.cc
This is the CI coverage of C++20 (and other C++ versions) that was discussed in https://github.com/dtolnay/cxx/pull/1432.  Let me start as a "draft" PR, to quickly check if the new CI steps actually pass.
=> Cover C++20 in CI (fixing `char8_t`-related problem there).

include/cxx.h
The reverse direction (which this function delegates to) is noexcept.
=> Mark operator+(difference_type, Slice<T>::iterator) as noexcept

gen/src/include.rs, include/cxx.h
This is needed for `std::ranges::contiguous_range`.
https://github.com/dtolnay/cxx/blob/0243229850588838dadaaee6e954195b7014b847/include/cxx.h#L265
=> Move ranges header to cxx.h

include/cxx.h, tests/ffi/tests.cc
PR #1367 added an explicit Slice constructor which allows constructing from any C++ container.
This adds a C++17 template deduction guide for that constructor which allows the Slice type to be inferred from the container's contained type.
So instead of this:
```cpp
void Foo(std::span<const uint8_t> data) {
foo(rust::Slice<const uint8_t>(data));
}
```
One could write this, omitting the `rust::Slice` template arguments:
```cpp
void Foo(std::span<const uint8_t> data) {
foo(rust::Slice(data));
}
```
=> Add template deduction guide for Slice constructor

MODULE.bazel
rules_cc@0.1.0 was yanked from [BCR](https://registry.bazel.build/modules/rules_cc) due to prematurely removing cc_proto_library, with the maintainers recommending remaining on 0.0.17. See https://github.com/dtolnay/cxx/pull/1422.
But recently 0.1.1 has been released and is being adopted in cxx's dependency graph, leading to the following warning from certain bazel commands:
> WARNING: For repository 'rules_cc', the root module requires module version rules_cc@0.0.17, but got rules_cc@0.1.1 in the resolved dependency graph. Please update the version in your MODULE.bazel or set --check_direct_dependencies=off
This PR updates to 0.1.1 as recommended in warning and [bazelbuild/rules_cc#268](https://github.com/bazelbuild/rules_cc/issues/268#issuecomment-2651269117).
=> Update rules_cc to 0.1.1

macro/src/expand.rs
```rust
mod ffi {
#[cfg(enabled)]
type A = crate::A;
}
}
```
When using the bridge above we need to ensure that all generated code also has the cfg attribute set. Before this change the following error would occur `cannot find type A in this scope`. This appears to be due to the generated verify block below that was not copying the attributes from the original type.
```rust
const _: fn() = ::cxx::private::verify_external_type::<A, ...>;
````
After this change the attributes are copied and therefore when the type is not compiled the verify block is also not compiled.
=> macro: ensure that cfg attrs are set for type alias verify generation

.bazelrc, .github/workflows/ci.yml, .gitignore, MODULE.bazel
This addresses the following build failure which is caused by file paths being too long for MSVC tools (see https://github.com/bazelbuild/rules_rust/issues/1120 for some extra context):
```
ERROR: C:/users/runneradmin/_bazel_runneradmin/dzh43mlk/external/rules_rust+/util/process_wrapper/BUILD.bazel:31:36: Compiling Rust (without process_wrapper) bin process_wrapper (6 files) [for tool] failed: (Exit 1): bootstrap_process_wrapper.bat failed: error executing Rustc command (from target @@rules_rust+//util/process_wrapper:process_wrapper) 
cd /d C:/users/runneradmin/_bazel_runneradmin/dzh43mlk/execroot/_main
SET CARGO_CFG_TARGET_ARCH=x86_64
SET CARGO_CFG_TARGET_OS=windows
SET CARGO_CRATE_NAME=process_wrapper
SET CARGO_MANIFEST_DIR=${pwd}/external/rules_rust+/util/process_wrapper
SET …
```
=> Use a shorter Bazel output base for Windows CI

.bcr/README.md, .bcr/config.yml, .bcr/metadata.template.json, .bcr/presubmit.yml, .bcr/source.template.json, MODULE.bazel
This change should add all the necessary components to support [bazel-contrib/publish-to-bcr](https://github.com/bazel-contrib/publish-to-bcr). All @dtolnay would need to do is follow the directions for that tool to setup automatic Bazel Central Registry deploys. Which I think is forking https://github.com/bazelbuild/bazel-central-registry and adding the app to their github account.
closes https://github.com/dtolnay/cxx/issues/1095
=> Added support for 'publish-to-bcr' tool

.bcr/source.template.json
Automated publishing of this module to the Bazel Central Registry is currently blocked with an error stating that MODULE.bazel can not be found. When I try to use `archive_override` to consume the published artifact for 1.0.146 I need to add `strip_prefix = "cxx-1.0.146"` to get around this same error. Adding that to the source.json template should fix the issue.
=> Add strip_prefix to unblock automated Bazel module publish

.bcr/config.yml
`["."]` is the default according to https://github.com/bazel-contrib/publish-to-bcr/tree/fa7d3c8ad241c2c0cde639eb2225be55816e9565/templates#optional-configyml
=> Delete redundant moduleRoots from bcr config

.bcr/source.template.json, .github/workflows/release.yml
This is required as mitigation for <https://blog.bazel.build/2023/02/15/github-archive-checksum.html>. The GitHub-generated `/archives/refs/tags` source archives are not guaranteed to have a stable checksum over time.
=> Add GitHub workflow to upload release archives with stable hash

.github/workflows/release.yml
https://github.com/dtolnay/cxx/actions/runs/13874499046/job/38825113504
```console
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```
=> Supply GitHub token to release workflow

.github/workflows/release.yml
With `xargs tar`, xargs might decide to split stdin across multiple tar commands. Since each of those would have the same `-f`, the final tgz will contain only paths from the last tar invocation, and could be silently missing contents.
=> Account for source tar filepaths surpassing xargs size limit

.github/workflows/release.yml
Reference: https://www.gnu.org/software/tar/manual/html_section/transform.html
_"Default is ‘rsh’, which means to apply transformations to both archive members and targets of symbolic and hard links."_
**Before:**
```console
$ tar xf cxx-1.0.148.tar.gz 
$ readlink cxx-1.0.148/flags/LICENSE-MIT
cxx-1.0.148/../LICENSE-MIT
```
**After:**
```console
$ tar xf cxx-1.0.148.tar.gz 
$ readlink cxx-1.0.148/flags/LICENSE-MIT
../LICENSE-MIT
```
Fixes https://github.com/bazelbuild/bazel-central-registry/pull/4055#issuecomment-2730277281.
=> Do not apply tar transform to symbolic link targets

book/src/binding/str.md, include/cxx.h, src/cxx.cc, tests/ffi/tests.cc
PTAL?
I am aware of https://github.com/dtolnay/cxx/pull/80 (adding a way to construct `rust::Str` from `std::string_view`, using a custom C++17-detection mechanism) and https://github.com/dtolnay/cxx/pull/410 (adding a way to construct `rust::String` from `std::string_view`, also using a custom C++17 detection mechanism).  But maybe we can still proceed with this PR given that:
* This PR is relatively simple - just adds one member (a conversion operator) to `rust::Str`.  I _think_ that adding such an **explicit** operator has close to zero risk of breaking existing users (unlike the other PRs where new constructor overloads may risk ambiguity or other resolution problems)
* Since the other PRs were raised, we were able to proceed with other C++-version-dependent APIs:
- …
=> Add an explicit conversion operator from `rust::Str` to `std::string_view`.

.github/workflows/release.yml
These are _probably_ identical for any `on: release:` triggered workflow run. In this repository, based on https://github.com/dtolnay/cxx/actions/runs/14095301876/job/39481323116, they are definitely identical. But there is no reason to mix and match. "Tag name" has the more obviously correct name.
=> Consistently use github.event.release.tag_name over github.ref_name

.github/workflows/release.yml
I want to contribute this workflow into the project template in https://github.com/bazel-contrib/publish-to-bcr. For that, it needs to accommodate tag names like `v1.0.0`.
https://github.com/bazel-contrib/publish-to-bcr/blob/65d4f0c00357d50ba19165993f673e56a7ddb500/src/domain/ruleset-repository.ts#L225-L230
=> Generalize tgz workflow to v-prefixed tag names

.bcr/source.template.json
The string value is no longer present in recent version of the publish-to-bcr template.
https://github.com/bazel-contrib/publish-to-bcr/blob/65d4f0c00357d50ba19165993f673e56a7ddb500/templates/.bcr/source.template.json
=> Clear integrity value in source.template.json

syntax/types.rs
=> Generate indirect placement for shared structs containing improper ctype

.bcr/metadata.template.json
https://github.com/bazelbuild/bazel-central-registry/blob/d561ba93f5ef84a15e5fbe086052f68e56fcea1b/metadata.schema.json
If the dtolnay user is deleted from GitHub, this PR prevents someone who takes over that username from publishing releases of this crate to Bazel Central Registry.
=> Fill in GitHub user ID for BCR publisher

.github/workflows/ci.yml
PTAL?
* I have temporarily reverted the fix at 1e10e24e6e4eceaf5776ee542dc4393bcd7f5b06 and verified that in that case the new CI has failed in my fork as expected: https://github.com/anforowicz/cxx/actions/runs/14339249757/job/40194179128
* It seems that the new CI step works without explicitly asking GitHub to install Clang.  I assume that `os: ubuntu` already includes pre-installed Clang.
* I made some arbitrary choices in this PR that I think don't matter that much in the end:
* For now I kept the old/current behavior in most steps where the `cc` crate picks a default compiler _somehow_ (by keeping the new `matrix.cc` empty for most of the matrix).  I guess I could have also preserved the old behavior by explicitly setting `cc` to `c++`.
* I only added a single Clang test step / …
=> Add Clang coverage to GitHub CI.

.github/workflows/release.yml
In order to adopt the new publish-to-bcr based on a reusable workflow (https://github.com/bazel-contrib/publish-to-bcr) instead of the deprecated app (https://github.com/apps/publish-to-bcr) we need not just the sources tgz published, but also a corresponding .tar.gz.intoto.jsonl like seen in https://github.com/aspect-build/rules_lint/releases/tag/v1.3.4.
=> Add permission for release_tgz workflow to write attestations

.github/workflows/release.yml
This is the new recommended process in https://github.com/bazel-contrib/publish-to-bcr. The GitHub App that published our previous few releases is legacy.
=> Add publish-to-bcr reusable workflow job

.github/workflows/release.yml
`verify-github-attestation` failed in https://github.com/bazelbuild/bazel-central-registry/pull/4324 because of https://github.com/bazel-contrib/publish-to-bcr/issues/262, but attestation has been made optional in publish-to-bcr by https://github.com/bazel-contrib/publish-to-bcr/pull/264.
=> Turn off publish-to-bcr attestation

.github/workflows/ci.yml
CI jobs have been succeeding anyway (because of the `continue-on-error: true`) but are producing the following alerts since https://github.com/dtolnay/cxx/pull/1437 and https://github.com/dtolnay/cxx/pull/1501.
=> Upload Cargo.lock artifact from just the default nightly job

.bazelignore
For example in this failure, Bazel is picking up some unexpected BUILD.bazel files inside of buck-out:
```console
$ bazel build ...
ERROR: /git/cxx/buck-out/v2/gen/root/904931f735703749/third-party/__cxx-1.0.158__/__srcs/cxx-631cdb11b2eb5c73/demo/BUILD.bazel:22:11: Compiling buck-out/v2/gen/root/904931f735703749/third-party/__cxx-1.0.158__/__srcs/cxx-631cdb11b2eb5c73/demo/src/blobstore.cc failed: (Exit 1): gcc failed: error executing CppCompile command (from target //buck-out/v2/gen/root/904931f735703749/third-party/__cxx-1.0.158__/__srcs/cxx-631cdb11b2eb5c73/demo:blobstore-sys) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++17' -MD -MF ... (remaining 18 arguments skipped)
Use --sandbox_debug to …
```
=> Prevent buck-out interfering with Bazel target patterns

gen/src/write.rs, macro/src/expand.rs, syntax/check.rs, syntax/mod.rs, syntax/parse.rs
Closes #1526 
This PR allows C++ method to be declared as `extern "C++-unwind"`, and the trampolines won't be decorated by `noexcept`.
=> Add "C++-unwind" support

gen/src/write.rs, syntax/namespace.rs
When a `main` function from a Rust library is linked into a C++ binary, previously one had to apply one of the following workarounds:
1. Wrap the Rust main in a C++ main:
```rust
// main.rs
fn rust_main() {...}
#[cxx::bridge]
mod ffi {
fn rust_main();
}
}
```
```cpp
// main.cpp
#include "path/to/src/main.rs.h"
int main() {
rust_main();
}
```
2. Declare an i32 return type for main in Rust:
```rust
fn main() -> i32 {
...
0
}
#[cxx::bridge]
mod ffi {
fn main() -> i32;
}
}
```
Otherwise the C++ compilation would fail trying to compile a cxx-generated source file like this:
```cpp
extern "C" {
void cxxbridge1$main() noexcept;
} // extern "C"
void main() noexcept {
cxxbridge1$main();
}
```
```console
<source>:5:1: error: 'main' must return 'int'
5 | void main() …
```
=> Add special case for Rust fn main

macro/src/expand.rs
Rustc nightly-2025-07-19 has begun warning about this. https://github.com/rust-lang/rust/pull/143845
```console
warning: `#[automatically_derived]` only has an effect on trait implementation blocks
--> demo/src/main.rs:23:12
|
23 |         fn put(&self, parts: &mut MultiBuf) -> u64;
|            ^^^
|
= note: `#[warn(unused_attributes)]` on by default
warning: `#[automatically_derived]` only has an effect on trait implementation blocks
--> demo/src/main.rs:24:12
|
24 |         fn tag(&self, blobid: u64, tag: &str);
|            ^^^
warning: `#[automatically_derived]` only has an effect on trait implementation blocks
--> demo/src/main.rs:25:12
|
25 |         fn metadata(&self, blobid: u64) -> BlobMetadata;
|            ^^^^^^^^
```
=> Delete #[automatically_derived] on impl blocks that are not trait impls

README.md, book/src/build/cargo.md, book/src/tutorial.md, demo/build.rs, gen/build/src/lib.rs, src/lib.rs
Adds `cargo:rerun-if-changed=<path>` for all files used by the bridge.
Note that when I went through all the `rerun-if-changed` cases, some of them did **not** include the .rs file - which may mean that even this repo is missing the needed tracking and this would fix those.
Fixes #1461
=> Auto-track all bridge files

Cargo.toml, tests/cpp_compile/mod.rs
If the test is interrupted before cleaning up a tempdir, they are cleaned up by `cargo clean` instead of remaining in /tmp.
=> Move C++ testing from /tmp to Cargo scratch directory

src/cxx.cc, src/result.rs
This makes `errorCopy` work whether it's copying an error message from a Rust `String` (no nul terminator) or `rust::Error`'s copy constructor (already nul terminated). Previously it only worked with nul terminated input.
=> Remove double-copy of message during rust::Error construction

book/src/binding/str.md
The presence of `size` and `length` confused me, adding a small comment to make it more clear for future readers.
=> [docs] add comment for rust::Str size and length

src/cxx.cc
This fix was necessary for my project (C++ depending on Rust) to compile. The approach here is conservative, only deferring from the existing behavior when the compiler *explicitly does not support exceptions* via feature-test macros. There may be other approaches here, like attempting to compile a test file with `throw`.
=> C++: Fix build on no-except compilers

tools/buck/toolchains/BUCK
Without this one of the tests is going to abort instead of throw.
> Error: rust::Vec index out of range. Aborting.
=> Turn on exception handling for Buck on Windows

src/cxx.cc
This test was passing prior to https://github.com/dtolnay/cxx/pull/1174 without needing https://github.com/dtolnay/cxx/pull/1556. This means there are cases where MSVC has working support for throw/catch without defining `__cpp_exceptions`.
https://github.com/dtolnay/cxx/blob/c6ab3793f72dee725b2d2ea6d74cf74deca63b46/tests/ffi/tests.cc#L385-L392
=> Disable exception detection on MSVC

book/src/shared.md, gen/src/write.rs, macro/src/expand.rs, syntax/attrs.rs, syntax/mod.rs, syntax/parse.rs, syntax/repr.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/test.rs, tests/ui/enum_align_unsupported.rs, tests/ui/enum_align_unsupported.stderr, tests/ui/struct_align.rs, tests/ui/struct_align.stderr
Add support for `#[repr(align(x))]` on bridge structs, closing #835. For the example code: 
```rust 
#[cxx::bridge]
mod ffi {
#[repr(align(4))]
struct S {
b: [u8; 4],
}
}
```
the following output was obtained using the cxx code generators:
```rust 
// -- snip 
#[repr(C)]
#[repr(align(4))]
pub struct S {
pub b: [u8; 4],
}
// -- snip
```
```cpp
#include <array>
#include <cstdint>
#include <type_traits>
struct S;
#ifndef CXXBRIDGE1_STRUCT_S
#define CXXBRIDGE1_STRUCT_S
struct alignas(4) S final {
::std::array<::std::uint8_t, 4> b;
using IsRelocatable = ::std::true_type;
};
#endif // CXXBRIDGE1_STRUCT_S
```
I believe it would be straightforward to extend this implementation for `#[repr(packed)]` as well. 
I was wondering whether to add support for enums but decided against it for now and made …
=> Add support for `#[repr(align(x))]` on bridge structs

gen/src/write.rs, macro/src/expand.rs, src/cxx.cc, src/shared_ptr.rs, src/unique_ptr.rs, tests/test.rs
This adds a way to create SharedPtr's from C++ pointers created with `new` (or via `unique_ptr`s).
I'm a new contributor here, let me know if I did this in a reasonable way, and I'm happy to put some effort in if this is something that's interesting.
=> Add UniquePtr::to_shared and SharedPtr::from_unmanaged

gen/src/write.rs, macro/src/expand.rs, src/cxx.cc, src/cxx_vector.rs, tests/test.rs
Efficient insertions into CxxVector requires reserving additional capacity. This also adds a way to query current capacity.
Also implement `extend`, which can use the size hint
=> CxxVector: implement reserve() and capacity()

Cargo.toml, gen/build/Cargo.toml, third-party/Cargo.toml
Versions 1.0.70 through 1.0.100 no longer compile in nightly-2025-08-31 due to a regression in std::env::split_paths.
This unbreaks our `-Zminimal-versions` CI.
=> Require cc version >=1.0.101

syntax/map.rs
I need a type that can be used as an associated type in a trait impl in an upcoming PR, and neither associated type impl trait nor type alias impl trait are stable yet, so I need a concretely named type.
=> Add a dedicated iterator type for OrderedMap::keys

macro/src/cfg.rs, macro/src/expand.rs, macro/src/generics.rs, macro/src/lib.rs, syntax/attrs.rs, syntax/cfg.rs, syntax/map.rs, syntax/trivial.rs, syntax/types.rs
For example:
```rust
#[cxx::bridge]
pub mod ffi {
extern "C++" {
type Thing;
}
#[cfg(aaaa)]
struct Wrapper {
name: String,
#[cfg(bbbb)]
thing: UniquePtr<Thing>,
}
#[cfg(cccc)]
#[cfg(dddd)]
fn mk() -> UniquePtr<Thing>;
}
}
```
This needs to expand to
```rust
...
#[cfg(any(all(aaaa, bbbb), all(cccc, dddd)))]
#[automatically_derived]
unsafe impl ::cxx::memory::UniquePtrTarget for Thing
...
```
because this is the configuration under which the required C++ symbols will exist on the generated C++ side.
=> Generate implicit impls with cfg matching uses

macro/src/expand.rs, src/lib.rs
These traits all can be named publicly since https://github.com/dtolnay/cxx/pull/762.
=> Generate cxx::memory and cxx:vector impls using public path of trait

macro/src/cfg.rs, syntax/cfg.rs, syntax/trivial.rs, syntax/types.rs
Previously, a module containing multiple conditional uses of an implicit impl, like this:
```rust
pub mod ffi {
extern "C++" {
type Thing;
}
#[cfg(target_os = "linux")]
fn a(_: UniquePtr<Thing>);
fn b(_: UniquePtr<Thing>);
fn c(_: UniquePtr<Thing>);
fn d(_: UniquePtr<Thing>);
}
}
```
would expand to a repetitive cfg on the UniquePtr impl:
```rust
...
#[cfg(any(any(target_os = "linux", target_os = "linux", target_os = "linux", target_os = "linux")))]
#[automatically_derived]
unsafe impl ::cxx::memory::UniquePtrTarget for Thing
...
```
This change makes it expand to `#[cfg(target_os = "linux")]` by accumulating `any` and `all` cfg elements in a set, instead of a vec.
=> Deduplicate elements of computed cfg

gen/src/cfg.rs
This saves subsequent `all`/`any` ComputedCfg work that is irrelevant to the C++ code generator.
=> Strip cfg expressions during evaluation

macro/src/expand.rs, tests/ui/deny_elided_lifetimes.rs, tests/ui/deny_elided_lifetimes.stderr
Previously, this would produce a warning inside macro-generated code.
```rust
#![warn(elided_lifetimes_in_paths)]
#[cxx::bridge]
mod ffi {
extern "C++" {
type Thing<'a> = path::to::Thing<'a>;
}
}
```
=> Fix elided_lifetimes_in_paths warning on extern types

.github/workflows/ci.yml, Cargo.toml, build.rs, flags/Cargo.toml, gen/build/Cargo.toml, gen/cmd/Cargo.toml, gen/lib/Cargo.toml, macro/Cargo.toml, third-party/Cargo.toml
This release stabilizes the `diagnostics` attribute namespace. https://blog.rust-lang.org/2024/05/02/Rust-1.78.0/#diagnostic-attributes
This will allow improving many of cxx's trait-related error messages, and deferring some errors from macro expansion to later in compilation, for example the suggestion to write `Pin<&mut T>` when using `&mut T` on an extern type that does not implement `Unpin`.
=> Raise required compiler to Rust 1.78

gen/src/write.rs, macro/src/expand.rs, src/rust_type.rs, syntax/trivial.rs, syntax/unpin.rs, tests/ffi/lib.rs, tests/ui/slice_of_pinned.rs, tests/ui/slice_of_pinned.stderr, tests/ui/slice_of_type_alias.stderr
```rust
// first crate
#[cxx::bridge]
pub mod ffi {
#[derive(ExternType)]
type Thing;
}
}
pub struct Thing {
...
}
```
```rust
// second crate
#[cxx::bridge]
pub mod ffi {
extern "C++" {
include!("first/src/lib.rs.h");
type Thing = first::Thing;
}
struct Struct<'a> {
things: &'a mut [Thing],
}
}
```
The soundness requirements are:
- `&[T]` requires `T: RustType` **or** `T: ExternType<Kind = Trivial>`
- `&mut [T]` requires `T: Unpin + RustType` **or** `T: Unpin + ExternType<Kind = Trivial>`
=> Support slice of type alias of Rust types

syntax/improper.rs, syntax/mod.rs, syntax/pod.rs, syntax/query.rs, syntax/types.rs
Previously, methods like `types.needs_indirect_abi(ty)` took ty as `&Type`, which made it unusable when looking at a `&NamedType`, such as in the case of a method receiver.
=> Generalize queries about types to work with a reference

.github/workflows/ci.yml
Some CI jobs are successfully installing clang-tidy-20 and some are not. This might help.
<p align="center"><img width="600" src="https://github.com/user-attachments/assets/6cf7cf3e-c043-4fcf-8db6-c16b4d76b91e" /></p>
<p align="center"><img width="600" src="https://github.com/user-attachments/assets/48fabf37-3179-4afb-835d-639f1db9f674" /></p>
=> Retrieve new packages before installing clang-tidy-20

Cargo.toml
Same reason as https://github.com/dtolnay/cxx/pull/1408.
The entry under `dev-dependencies` is not sufficient for enforcing this. It was still possible to have a version mismatch.
```console
$ cargo tree --depth=1
repro v0.0.0
└── cxx v1.0.180
[build-dependencies]
[build-dependencies]
└── cxx-build v1.0.179
```
=> Enforce cxx-build version equality

.github/workflows/ci.yml
Recently the CI jobs that run apt-get have been extremely slow. Sometimes over 10 minutes to install clang-tidy-20 or lld. This might help.
=> Disable initramfs update and man-db update

gen/src/pragma.rs, gen/src/write.rs
Closes #1216.
For Clang maybe we could have used:
```diff
- extern "C" {
- rust::Vec<...> cxxbridge1$...$data_processor$0(...) noexcept;
- }
+ rust::Vec<...> trampoline(...) noexcept asm("cxxbridge1$...$data_processor$0");
```
But I did not figure out any alternative that would work with MSVC.
=> Suppress -Wreturn-type-c-linkage on rust::Fn trampoline

gen/src/pragma.rs
This rules out the possibility of forgetting to update pragma::write after adding a new field in Pragma.
=> Convert pragma::write to exhaustive match

gen/src/write.rs
PTAL?
Just a minor refactoring / no intended behavior changes - this PR:
* Extracts `fn write_binary_bitwise_op` out of `fn write_enum_operators` - the only difference between `BitAnd` / `BitOr` / `BitXor` branches were the `op` used (`&` or `|` or `^`) in 1) the name of `operatorFOO` and 2) in actual expression.
* Also names `enum_name` so that it can be directly used in formatting specifiers (instead of using `{}` and then passing `enm.name.cxx` as an arg)
=> Deduplicate parts of write_enum_operators into write_binary_bitwise_op.

build.rs
`links` needs to be bumped when releasing a major version.
=> Enforce that package.links matches expected format
