gen/write.rs
=> Resolve Wreturn-type-c-linkage warnings

cmd/src/main.rs, gen/include.rs
=> Emit cxxbridge

.travis.yml
=> Add macos and cargo test

.gitignore, .travis.yml, BUILD, WORKSPACE, build/rust.bzl, demo-cxx/BUILD, demo-rs/BUILD, third-party/BUILD
=> Add bazel targets

include/cxxbridge.h
=> Protect from ADL in Box construction and assignment

src/paths.rs
`fs::canonicalize` on Windows produces UNC paths which cl.exe is unable to handle in includes.
- https://github.com/rust-lang/rust/issues/42869
- https://github.com/alexcrichton/cc-rs/issues/169
Required for #25.
=> Remove reliance on fs::canonicalize on Windows

.travis.yml
=> Enable windows CI

gen/out.rs
Not immediately used, but necessary for implementing `namespace rust { inline namespace cxxbridge { ... } }` for #46.
=> Support nested blocks in C++ emitter

gen/write.rs, syntax/atom.rs
=> Add f32 and f64 types

include/cxx.h
=> Make it explicit when going from T to Box<T>

src/paths.rs
=> Handle failures to symlink on windows

syntax/parse.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
=> Allow &self without a type when the block only has one type

README.md
I published the existing releases retroactively at https://github.com/dtolnay/cxx/releases and will include release notes for future releases.
=> Link to release notes from readme

syntax/check.rs, tests/ui/reference_to_reference.rs, tests/ui/reference_to_reference.stderr
=> Disallow passing a reference to a reference.

src/cxx.cc, src/symbols/rust_vec.rs
=> Add support for rust::Vec<bool>

gen/src/error.rs
Fixes #174.
Before:
```console
error[cxxbridge]: unsupported type
┌─ lib.rs:16:12
│
16 │         y: what,
│            ^^^^ unsupported type
│
error[cxxbridge]: structs without any fields are not supported
┌─ lib.rs:13:5
│
13 │     struct Empty {}
│     ^^^^^^^^^^^^^^^ structs without any fields are not supported
│
```
After:
```console
error[cxxbridge]: structs without any fields are not supported
┌─ lib.rs:13:5
│
13 │     struct Empty {}
│     ^^^^^^^^^^^^^^^ structs without any fields are not supported
│
error[cxxbridge]: unsupported type
┌─ lib.rs:16:12
│
16 │         y: asdf,
│            ^^^^ unsupported type
│
```
=> Sort errors reported by line number

gen/src/find.rs
=> Find cxx::bridge mod nested inside another mod

src/lib.rs
=> Add crosslink icons to top of rustdoc

demo-cxx/BUCK, demo-cxx/BUILD, demo-cxx/demo.cc, demo-rs/build.rs
=> Switch demo code to using std::make_unique

.clang-format, gen/src/include.rs, gen/src/write.rs, include/cxx.h
Fixes #151.
Before: https://github.com/dtolnay/cxx/blob/1385ca42b2f94cd83b9556452316b5976842da35/include/cxx.h#L139-L199
After: https://github.com/dtolnay/cxx/blob/2a2b9ad1f527c45b237cef8757ee20bb7b790282/include/cxx.h#L127-L149
=> Move all function implementations to the bottom of cxx.h

tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs, tests/ui/enum_match_without_wildcard.stderr, tests/ui/opaque_not_sized.stderr, tests/ui/wrong_type_id.stderr
#232, as well as some error message formatting changes that landed in nightly-2020-06-27, nightly-2020-07-07, nightly-2020-07-15.
=> Unbreak ui tests

gen/src/include.rs, gen/src/write.rs, include/cxx.h
=> Include <new> when placement new is used

include/cxx.h, src/cxx.cc
=> Add rust::String(const char *, size_t) constructor

gen/src/include.rs, gen/src/out.rs, gen/src/write.rs
Otherwise it does not take effect -- see https://github.com/dtolnay/cxx/pull/243#issuecomment-667230084. This fixes a bug introduced in 9c68b1a0c67cb2830eeca0e5206f97b4a710ae7a.
=> #pragma once needs to be above includes

include/cxx.h, src/cxx.cc
Following up on https://github.com/dtolnay/cxx/pull/257#pullrequestreview-476382515.
=> Unify the way that String construction and Vec indexing throw

macro/src/expand.rs, src/rust_string.rs, src/rust_vec.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h
=> Handle &mut reference in more places

macro/src/expand.rs, src/cxx.cc, src/rust_vec.rs, src/symbols/rust_string.rs, src/symbols/rust_vec.rs, syntax/check.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h
=> Implement Vec<String>

src/cxx.cc, src/cxx_vector.rs, syntax/check.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h
=> Implement CxxVector<CxxString>

syntax/mod.rs, syntax/namespace.rs, syntax/qualified.rs
=> Permit rust keywords in C++ qualified paths

syntax/namespace.rs, syntax/qualified.rs
=> Allow namespace to be given as a quoted string

macro/src/lib.rs, macro/src/type_id.rs, syntax/mod.rs
=> Accept unquoted path in type_id macro

gen/src/include.rs, gen/src/write.rs, include/cxx.h
=> Update case of basetsd.h import to support cross compilation

gen/src/write.rs, macro/src/expand.rs, tests/ffi/lib.rs
=> Fix return Result<Box<T>> from Rust to C++ [v2]

.devcontainer/Dockerfile, .devcontainer/build.Dockerfile, .devcontainer/devcontainer.json, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json
=> Create devcontainer configuration to use with GitHub Codespaces

demo/BUCK, demo/BUILD, tests/BUCK, tests/BUILD, tools/bazel/rust_cxx_bridge.bzl, tools/buck/rust_cxx_bridge.bzl
=> Factor out genrules to rust_cxx_bridge.bzl

macro/src/expand.rs, src/cxx_vector.rs, tests/ffi/lib.rs, tests/ffi/tests.cc
=> Add API to get slice from CxxVector

macro/src/expand.rs, src/lib.rs, syntax/types.rs
=> Touch up PR 325

gen/src/write.rs
FYI @adetaylor.
This reflects the bottom of my comment from https://github.com/dtolnay/cxx/issues/313#issuecomment-698699152.
=> Add some thoughts about the triviality static assertions

gen/src/write.rs, syntax/impls.rs, syntax/mod.rs, syntax/parse.rs
This will be needed for a correctly positioned error in #368.
=> Track span information of include statements

gen/src/file.rs, macro/src/lib.rs, syntax/attrs.rs, syntax/namespace.rs, tests/ffi/class_in_ns.rs, tests/ffi/extra.rs, tests/ffi/lib.rs
Thanks to sbrocket for this parsing code.
=> Switch to #[namespace = A::B] syntax.

src/cxx.cc
Closes #343. We treat `rust::String(nullptr, 0)` and `rust::Str(nullptr, 0)` both as empty strings, matching `std::string(nullptr, 0)`.
This PR opts to keep the UB on construction from `(nullptr)` and `(nullptr, >0)`, also matching std::string.
=> Match std::string's behavior on (nullptr, 0) construction

src/cxx.cc
=> Add asserts to protect string construction from nullptr when building with assertions

gen/src/write.rs, tests/ffi/lib.rs
=> Namespace forward declarations

gen/src/builtin.rs, gen/src/mod.rs, gen/src/out.rs, gen/src/write.rs
=> Move builtin tracking bools to module

gen/src/out.rs
This recognizes and eliminates patterns of consecutive `out.end_block(_)` + `out.begin_block(_)` leaving and entering the same block.
In preparation for a topological sort (#292), which will require relatively unstructured jumping between namespaces.
=> Recognize identical block being closed and opened

gen/src/alphasort.rs, gen/src/write.rs
Starting to take advantage of #403.
=> Move set_namespace to individual items

macro/src/expand.rs
The implementation is half as much code, and generates better output too. e.g for a C++ function returning Result\<&str\>, before:
```rust
let mut __return = ::std::mem::MaybeUninit::<::cxx::private::RustStr>::uninit();
__do(__return.as_mut_ptr()).exception()?;
::std::result::Result::Ok(__return.assume_init()).map(|r| r.as_str())
```
after:
```rust
let mut __return = ::std::mem::MaybeUninit::<::cxx::private::RustStr>::uninit();
__do(__return.as_mut_ptr()).exception()?;
::std::result::Result::Ok(__return.assume_init().as_str())
```
=> Simplify lowering of fallible extern C++ return values

gen/src/toposort.rs, gen/src/write.rs, tests/ffi/lib.rs
=> Implement struct toposort

gen/build/src/deps.rs, gen/build/src/lib.rs
This structure is going to be necessary for #417.
=> Start building structured dependency information

gen/build/src/lib.rs
Part of #417.
The field is still #\[doc(hidden)\] for now but documentation will follow once the rest of CFG described by #417 is ready.
=> Implement CFG.exported_header_links

gen/build/src/lib.rs
=> Implement CFG.exported_header_prefixes

gen/build/src/lib.rs
For example if A depends on B and C, and B and C both depend publicly on D, then D's dirs should appear just once on A's search path. Otherwise we get potentially exponentially large search paths.
#417
=> Deduplicate dirs reachable via multiple transitive dependencies

gen/build/src/error.rs, gen/build/src/lib.rs
=> Validate that `links` attribute is set if exporting headers

gen/build/src/error.rs, gen/build/src/lib.rs
=> Validate that all exported_header_prefixes/_links are used

gen/build/Cargo.toml, gen/build/src/cfg.rs, third-party/Cargo.lock
=> Document CFG's exported header support

.github/workflows/site.yml, book/book.toml
This pulls in https://github.com/rust-lang/mdBook/pull/1311.
=> Upgrade to mdbook 0.4.4 for CNAME file support

gen/src/write.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/test.rs
Fixes https://github.com/dtolnay/cxx/issues/376#issue-731871040.
=> Support methods/member functions on shared structs

macro/src/expand.rs, tests/ui/result_no_display.stderr
=> Improve placement of diagnostic on Result without Display impl

book/book.toml, book/build.js, book/css/cxx.css, book/package-lock.json, book/package.json
https://github.com/rust-lang/mdBook/issues/1383
=> Preapply hljs to provide highlighting for browsers with JS off

.github/workflows/ci.yml, README.md, WORKSPACE, build.rs, demo/src/main.rs, gen/lib/tests/test.rs, src/extern_type.rs, src/lib.rs, syntax/parse.rs, tests/cxx_gen.rs, tests/ffi/extra.rs, tests/ffi/lib.rs, tests/ffi/module.rs, tests/ui/disallow_lifetime.rs, tests/ui/reference_to_reference.rs, tests/ui/unnamed_receiver.rs, tests/ui/unrecognized_receiver.rs
As described in https://www.reddit.com/r/rust/comments/ielvxu/the_cxx_debate/g2i1r7a/.
=> Enforce unsafe surrounding block on safe-to-call functions

syntax/mod.rs, syntax/parse.rs, syntax/types.rs
=> Fix missing cstdint import when generating enums

book/diagram/.gitignore, book/diagram/Makefile, book/diagram/overview.ascii, book/diagram/overview.svg
=> Add overview svg

book/book.toml, book/src/SUMMARY.md, book/src/about.md, book/src/async.md, book/src/attributes.md, book/src/binding/box.md, book/src/binding/cxxstring.md, book/src/binding/cxxvector.md, book/src/binding/fn.md, book/src/binding/result.md, book/src/binding/slice.md, book/src/binding/str.md, book/src/binding/string.md, book/src/binding/uniqueptr.md, book/src/binding/vec.md, book/src/bindings.md, book/src/build/bazel.md, book/src/build/cargo.md, book/src/build/cmake.md, book/src/build/other.md, book/src/building.md, book/src/concepts.md, book/src/context.md, book/src/extern-c++.md, book/src/extern-rust.md, book/src/index.md, book/src/overview.svg, book/src/reference.md, book/src/shared.md, book/src/tutorial.md
=> Book content

.clang-tidy, .github/workflows/ci.yml
This actually didn't properly work on my fork. I'm a bit puzzled by Github Actions.. Let's see here.
Fixes #390.
=> Add clang-tidy CI check

book/src/binding/vec.md, include/cxx.h
=> Add rust::Vec mutable iterator

book/src/binding/slice.md, include/cxx.h
=> Add iterator for rust::Slice

.clang-tidy, book/src/binding/str.md, book/src/binding/string.md, include/cxx.h, src/cxx.cc
=> Add String and Str iterators

book/src/binding/vec.md, include/cxx.h
=> Add non-const indexing for rust::Vec

include/cxx.h, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
My attempt at addressing #150.
=> Implement the random access iterator for rust::Vec

gen/src/builtin.rs, gen/src/write.rs
=> Respect class-specific member operator new in MaybeUninit allocation

.clang-tidy, src/cxx.cc, src/shared_ptr.rs
=> Support shared_ptr of primitives

book/src/binding/vec.md, gen/src/write.rs, include/cxx.h, macro/src/expand.rs, src/cxx.cc, src/rust_vec.rs, src/symbols/rust_vec.rs
```diff
class Vec final {
...
+   size_t capacity() const noexcept;
};
```
=> Expose Vec capacity to C++

book/src/binding/vec.md, include/cxx.h
```diff
class Vec final {
...
+   Vec(const Vec &);
+   Vec &operator=(const Vec &);
};
```
=> Add Vec copy constructor and copy assignment operator

include/cxx.h
=> Fix omitted typenames incompatible with Visual C++ 2015

gen/src/write.rs, include/cxx.h, macro/src/expand.rs
=> Free Box allocation on T constructor exception

book/src/binding/string.md, include/cxx.h, src/cxx.cc, src/symbols/rust_string.rs, tests/ffi/tests.cc
Matches https://en.cppreference.com/w/cpp/string/basic_string/c_str.
#224
=> Add c_str() member function for rust::String

gen/src/write.rs, macro/src/derive.rs, macro/src/expand.rs, syntax/ident.rs, syntax/mod.rs, syntax/parse.rs, tests/ffi/lib.rs, tests/ffi/tests.h, tests/test.rs
=> Support cxx_name/rust_name attributes on enum variants

gen/src/write.rs
This provides SFINAE support for distinguishing opaque types based on `std::is_base_of<rust::Opaque, T>::value`.
=> Set rust::Opaque as base class of all opaque Rust types

book/src/binding/slice.md, include/cxx.h, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
https://en.cppreference.com/w/cpp/named_req/RandomAccessIterator
=> Expand Slice iterator to be random access iterator

include/cxx.h
This makes it possible to obtain the stride from a Rust symbol in the case of slices of opaque Rust types (#532).
Currently it's still always using `sizeof(T)` for the stride in this PR but a separate PR will make it work with `rust::size_of<T>()` (from #597).
=> Track stride as runtime value in Slice iterator

syntax/check.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
=> Allow passing slice of extern Rust type across FFI

gen/src/builtin.rs, gen/src/write.rs, include/cxx.h, macro/src/expand.rs, src/cxx.cc, src/symbols/rust_sizeof.rs, src/symbols/rust_vec.rs, syntax/check.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
=> Support opaque Rust types in a rust::Slice

macro/src/expand.rs, syntax/impls.rs, syntax/mod.rs, syntax/parse.rs, tests/ui/deny_missing_docs.stderr
=> Preserve doc attributes on struct fields

gen/src/nested.rs, macro/src/expand.rs, syntax/mod.rs, syntax/parse.rs, tests/ui/deny_missing_docs.stderr, tests/ui/enum_match_without_wildcard.stderr
=> Fix span placement for rust lints inside of bridge module

syntax/parse.rs
=> Support rename attributes on struct fields

book/src/binding/slice.md, book/src/binding/str.md, include/cxx.h, src/cxx.cc
See https://github.com/dtolnay/cxx/pull/643#issuecomment-753533801.
=> Restore swapping Str and Slice in member function form only

macro/src/derive.rs, macro/src/expand.rs, syntax/parse.rs, tests/ffi/lib.rs, tests/ui/multiple_parse_error.stderr
```rust
#[cxx::bridge]
mod ffi {
pub struct Struct<'a> {
s: &'a str,
}
}
```
=> Support lifetimes on shared structs

gen/src/builtin.rs, gen/src/include.rs
=> Include <cassert> where needed in generated code

src/cxx_string.rs, tests/cxx_string.rs
=> Allow Send/Sync of let_cxx_string

macro/src/expand.rs, macro/src/lib.rs, macro/src/type_id.rs, src/lib.rs, src/type_id.rs
=> Enable expanding type_id macro in a crate with cxx renamed

include/cxx.h, src/cxx.cc
=> Disallow assignment to rvalue

syntax/check.rs, tests/ui/ptr_in_fnptr.rs, tests/ui/ptr_in_fnptr.stderr
Fixes https://github.com/dtolnay/cxx/pull/689#discussion_r599192164.
Follow-up to #689.
=> Detect raw pointer argument inside of function pointer

gen/src/write.rs, syntax/check.rs, tests/ui/ptr_unsupported.rs, tests/ui/ptr_unsupported.stderr
Fixes https://github.com/dtolnay/cxx/pull/689#discussion_r599185678, fixes https://github.com/dtolnay/cxx/pull/689#discussion_r599186475.
=> Pointer to pointer, pointer to reference, reference to pointer

book/src/binding/rawptr.md
I think this will be more relatable than the previous example with ComplexHierarchicContainer. Even in C++ libraries it's common that command line arguments are manipulated via raw pointer.
- folly: https://github.com/facebook/folly/blob/82fce98f1ec9cfe70b1bec5788c437dacd83c512/folly/init/Init.h#L66
- gflags: https://github.com/gflags/gflags/blob/827c769e5fc98e0f2a34c47cef953cc6328abced/src/gflags.h.in#L348
- glog: https://github.com/google/glog/blob/d4e8ebab7e295f20f86cae9557da0d5087a02f73/src/glog/logging.h.in#L532
#689
=> Rewrite raw ptr book page with example involving argc/argv

macro/src/expand.rs
Previously:
```console
error: `extern` block uses type `String`, which is not FFI-safe
--> src/main.rs:13:27
|
13 |         unsafe fn test(x: *mut String);
|                           ^^^^^^^^^^^ not FFI-safe
```
#689
=> Handle pointer cast of non-ffi-safe pointer target types

gen/src/builtin.rs, include/cxx.h
=> Fix warning on unused unsafe_bitcopy variable

syntax/check.rs, syntax/tokens.rs, tests/ui/mut_return.rs, tests/ui/mut_return.stderr
=> Permit mut from ref in unsafe-to-call signatures

gen/src/write.rs
=> Support reference return type from fallible Rust function

macro/src/expand.rs, tests/ffi/module.rs, tests/ffi/tests.cc, tests/ffi/tests.h
Fixes https://github.com/google/autocxx/issues/319.
=> Handle pinned reference argument pointing to improper ctype

macro/src/expand.rs, tests/ffi/module.rs, tests/ffi/tests.cc, tests/ffi/tests.h
=> Fix pinned returned reference to improper ctype extern type

src/rust_slice.rs, src/rust_str.rs
=> Revamp RustStr and RustSlice ABI to match cxx.h

src/rust_string.rs, src/rust_vec.rs, src/symbols/rust_vec.rs
=> Revamp RustString and RustVec ABI to match cxx.h

macro/src/expand.rs
=> Insert void ptr casts for invalid Box and UniquePtr ctypes

macro/src/expand.rs
This strangely turns out to be the reason for #744 triggering in the expanded code but not in macro's output tokens.
=> Preserve token spans everywhere possible in expand_extern_type

gen/src/write.rs, syntax/doc.rs
=> Fix placement of C++ comments on member function decls

gen/src/builtin.rs, gen/src/write.rs, macro/src/expand.rs, src/cxx.cc, src/cxx_vector.rs, tests/ffi/tests.cc, tests/test.rs
=> Add CxxVector::push in Rust

macro/src/expand.rs
=> Work around redundant_closure lint in old clippys

macro/Cargo.toml, macro/src/clang.rs, third-party/Cargo.lock
These files get somewhat large (tens of megabytes).
=> Memory-map AST file instead of reading to memory

book/src/binding/str.md, book/src/binding/string.md, include/cxx.h, src/cxx.cc
=> Add `bool empty() const noexcept` to Str, String

gen/build/src/out.rs, gen/src/fs.rs
=> Fix race condition between simultaneous build scripts creating symlinks

src/c_char.rs, src/lib.rs, src/symbols/rust_vec.rs
=> Vendor c_char definition from libstd

src/unwind.rs
=> Implement a no_std catch_unwind mechanism

Cargo.toml, src/exception.rs
=> Add a std feature to conditionalize the Error impl on cxx::Exception

BUCK, BUILD, Cargo.toml, src/c_char.rs, src/cxx_string.rs, src/exception.rs, src/extern_type.rs, src/lib.rs, src/result.rs, src/rust_string.rs, src/rust_vec.rs, src/symbols/exception.rs, src/symbols/rust_str.rs, src/symbols/rust_string.rs, src/symbols/rust_vec.rs
=> Add alloc feature behind feature gate

macro/src/clang.rs, macro/src/derive.rs, macro/src/expand.rs, src/lib.rs
=> Eliminate references to ::std from generated code

.github/workflows/ci.yml, src/c_char.rs, src/lib.rs, tests/ffi/Cargo.toml
=> Add CI builds on no_std and no_alloc

macro/src/expand.rs
Previously it was possible for a panic inside of a custom implementation of `Drop`, `PartialEq`, `PartialOrd`, or `Hash` on an `extern "Rust"` opaque type to hit the C boundary, which is UB.
```rust
// src/main.rs
#[cxx::bridge]
mod ffi {
type Struct;
fn make_box() -> Box<Struct>;
}
include!("example/include/repro.h");
fn repro();
}
}
pub struct Struct;
fn make_box() -> Box<Struct> {
Box::new(Struct)
}
impl Drop for Struct {
fn drop(&mut self) {
panic!();
}
}
fn main() {
ffi::repro();
}
```
```cpp
// include/repro.h
#pragma once
void repro();
```
```cpp
// src/repro.cc
#include "example/include/repro.h"
#include "example/src/main.rs.h"
void repro() {
auto box = make_box();
(void)box;
}
```
**Before** (UB)
```console
thread 'main' panicked at 'explicit …
```
=> Wrap all trait impls exposed to C++ in prevent_unwind

BUCK, BUILD, gen/build/Cargo.toml, gen/build/src/cfg.rs, gen/build/src/intern.rs, third-party/BUCK, third-party/BUILD, third-party/Cargo.lock
The non-macro-based API is in favor these days.
=> Replace lazy_static with once_cell

syntax/attrs.rs, syntax/cfg.rs, syntax/mod.rs
=> Add parser for cfg expressions

gen/src/cfg.rs, gen/src/mod.rs, syntax/attrs.rs, syntax/cfg.rs
=> Run cfg evaluator to strip syntax tree

gen/cmd/Cargo.toml, gen/cmd/src/app.rs, third-party/BUCK, third-party/BUILD, third-party/Cargo.lock
Context: https://epage.github.io/blog/2022/06/clap-32-last-call-before-40/
Closes #1057. Closes #1058.
=> Update to clap 3.2

macro/src/load.rs, macro/src/tokens.rs, src/c_char.rs, src/lib.rs, syntax/tokens.rs
=> No-std fixes for Box, String, Pin, c_char

macro/src/type_id.rs, syntax/qualified.rs, tests/ui/raw_ident_namespace.rs, tests/ui/raw_ident_namespace.stderr
=> Support raw identifiers in namespace attribute

tests/ui/unpin_impl.rs, tests/ui/unpin_impl.stderr
=> Restore unpin_impl.rs UI test after `need_type_info` ICE has been fixed

gen/src/write.rs
This provides a central place to apply whatever change might be needed for #669.
=> Extract a function for writing docs in generated C++

gen/build/Cargo.toml, gen/build/src/cfg.rs, gen/build/src/lib.rs, gen/src/mod.rs, gen/src/write.rs, third-party/Cargo.lock
=> Doxygen comments

syntax/names.rs, tests/ffi/lib.rs, tests/ffi/tests.cc
=> Support cxx_name containing name that is Rust keyword

macro/src/expand.rs
See https://github.com/dtolnay/cxx/issues/1162.
=> Suppress dead_code on generated enum variants

macro/src/derive.rs, macro/src/expand.rs
=> Suppress various pedantic clippy lints

gen/build/src/out.rs
Attempt to relativize symlinks. Fixes #1250.
- Do not relativize where target or link are relative paths.
- Do not relativize where CARGO_TARGET_DIR is set, as this indicates that relativizing might not be helpful.
- Do not relativize where source or target contain `..`
It feels a bit weird where it is because the module is filesystem-specific, cxx-agnostic, but I justified it to myself on the basis that it's _cxx's_ interface for interacting with the filesystem specifically for the purpose of writing output.
=> Relativize symlinks where possible

gen/build/src/lib.rs, gen/build/src/out.rs, gen/build/src/paths.rs
=> Fix symlink paths during copy on Windows

gen/build/src/out.rs
=> Verify relativized symlink path

src/cxx_vector.rs
Fixes https://github.com/dtolnay/cxx/issues/1297
=> Document how to implement VectorElement

meson.build
Commits have more detailed explanations. Let me know if you have any questions.
Thanks
=> meson: define project version, disable dollar-in-identifier-extension warnings for now

book/build.js
The previous way just hardcoded that the 3rd &lt;script&gt; tag is the relevant one.
=> Perform mdbook js patching more exactly

book/build.js
```diff
diff -r build.before/concepts.html build/concepts.html
212c212
< </span><span class="boring">}</code></pre>
---
> </span><span class="boring">}</span></code></pre>
```
=> Fix missing </span> on last boring line

book/build.js, book/package-lock.json, book/package.json
https://cheerio.js.org/blog/cheerio-1.0
=> Update cheerio to 1.0.0

book/src/binding/string.md
From https://github.com/dtolnay/cxx/pull/1437.
=> Document char8_t rust::String constructors

src/unique_ptr.rs
This commit implements forwarding of `Seek` trait implementation from `UniquePtr<T>` to the pointee type.  This is quite similar to how `Box<T>` also forwards - see
https://doc.rust-lang.org/std/boxed/struct.Box.html#impl-Seek-for-Box%3CS%3E
This commit has quite similar, orphan-rule-related motivation as the earlier https://github.com/dtolnay/cxx/pull/1368 which covered the `Read` trait.  A more specific motivating example is https://crbug.com/400455848 where `png` crate changed the old `Read` constraint to `Read + Seek + ...`.
=> `impl<T> Seek for UniquePtr<T> where ... Pin<&a mut T> : Seek`.

.github/workflows/ci.yml, build.rs, src/unique_ptr.rs
Followup to #1454.
@anforowicz
=> Forward Seek::seek_relative on Rust 1.80+

src/unique_ptr.rs
=> More UniquePtr trait impls: Eq, PartialOrd, Ord, Hash

src/shared_ptr.rs
Like the ones for UniquePtr: #1446 and #1456.
=> More SharedPtr trait impls

.bcr/presubmit.yml
See https://github.com/bazelbuild/bazel-central-registry/pull/4045#pullrequestreview-2687736007
=> Fix Bazel presubmit build targets

gen/src/builtin.rs, gen/src/include.rs
Needs to match this:
https://github.com/dtolnay/cxx/blob/4661af81a3388c2173189564f7375971b8a5039c/include/cxx.h#L23-L25
=> Generate `#include <string_view>`

gen/src/mod.rs, gen/src/primitive.rs, gen/src/write.rs
=> Zero-initialize primitive fields of shared structs in default constructor

.github/workflows/ci.yml
Let me start this as a **draft** PR to double-check that the CI passes with the new flags.
=> Add `-Wall` and `-Werror` to `CXXFLAGS` used by GitHub CI.

macro/src/expand.rs
https://blog.rust-lang.org/2024/10/17/Rust-1.82.0/#native-syntax-for-creating-a-raw-pointer
=> Resolve borrow_as_ptr clippy lints in generated code

gen/src/write.rs, macro/src/expand.rs, syntax/attrs.rs, syntax/check.rs, syntax/mangle.rs, syntax/mod.rs, syntax/parse.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/ffi/tests.h, tests/test.rs
One of the commits from #1430.
=> Static member fn [Extracted from PR 1430]

.github/workflows/ci.yml
Mistake in https://github.com/dtolnay/cxx/pull/1563
=> Fix missing MSVC std version flags

book/src/shared.md, gen/src/builtin.rs, gen/src/write.rs, macro/src/expand.rs, syntax/attrs.rs, syntax/mod.rs, syntax/parse.rs, syntax/repr.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/test.rs, tests/ui/enum_align_unsupported.rs, tests/ui/enum_align_unsupported.stderr, tests/ui/repr_align_suffixed.rs, tests/ui/repr_align_suffixed.stderr, tests/ui/repr_unsupported.rs, tests/ui/repr_unsupported.stderr, tests/ui/struct_align.stderr
Followups to https://github.com/dtolnay/cxx/pull/902.
=> Improve repr(align) implementation

gen/src/write.rs, macro/src/expand.rs, src/cxx.cc, src/shared_ptr.rs, src/unique_ptr.rs, tests/test.rs
https://github.com/dtolnay/cxx/pull/1005
=> Modifications to PR 1005

src/shared_ptr.rs
=> Add SharedPtr mut and pointer accessors

gen/src/write.rs, macro/src/expand.rs, src/cxx_vector.rs
=> Fixes to PR 1300

gen/src/builtin.rs, gen/src/write.rs, macro/src/expand.rs, src/shared_ptr.rs, tests/ffi/lib.rs, tests/ffi/tests.h, tests/test.rs
=> Support shared ptr with not destructible T

syntax/types.rs, tests/ui/duplicate_method.stderr
=> Fix duplication checking of static member functions

gen/src/builtin.rs, gen/src/builtin/trycatch_detail.h, gen/src/guard.rs, gen/src/mod.rs, gen/src/pragma.rs, gen/src/write.rs, src/cxx.cc, syntax/symbol.rs
=> Disable -Wdollar-in-identifier-extension in generated code

macro/src/lib.rs, syntax/check.rs, syntax/doc.rs, syntax/error.rs, syntax/file.rs, syntax/instantiate.rs, syntax/map.rs, syntax/mod.rs, syntax/resolve.rs, syntax/symbol.rs, syntax/trivial.rs, syntax/types.rs, syntax/unpin.rs
https://blog.rust-lang.org/2024/09/05/Rust-1.81.0/#expect-lint
=> Change allow(dead_code) to conditional expect(dead_code)

macro/src/expand.rs, tests/ffi/lib.rs, tests/ffi/tests.cc, tests/test.rs
=> Pass Rust method receiver to C function as pointer not reference

gen/src/mod.rs, gen/src/nested.rs, macro/src/attrs.rs, macro/src/derive.rs, macro/src/expand.rs, macro/src/lib.rs, syntax/attrs.rs, syntax/mod.rs, syntax/parse.rs, syntax/tokens.rs, tests/BUCK, tests/BUILD.bazel, tests/ffi/Cargo.toml, tests/ffi/lib.rs, third-party/BUCK, third-party/Cargo.lock, third-party/Cargo.toml, third-party/bazel/BUILD.bazel, third-party/bazel/BUILD.serde-1.0.219.bazel, third-party/bazel/BUILD.serde_derive-1.0.219.bazel, third-party/bazel/defs.bzl, third-party/fixups/serde/fixups.toml
=> Apply passthrough attrs like serde only to main type

.github/workflows/ci.yml
=> Add Emscripten CI job

macro/src/expand.rs
=> Fix 'expected a FnOnce() closure' on unsafe Rust fn with no args

syntax/check.rs
All of these locations need to be visited when a new derive is added to the `Trait` enum.
=> Convert derive checking to exhaustive matches

macro/src/expand.rs
For this API:
```rust
type Thing<'a>;
fn f<'b, 'c>(self: &Thing<'b>, i: &'c CxxString);
}
```
Before:
```rust
impl<'b, 'c> Thing<'b> {
pub fn f(&self, i: &'c CxxString) {...}
}
```
After:
```rust
impl<'b> Thing<'b> {
pub fn f<'c>(&self, i: &'c CxxString) {...}
}
```
This is a prerequisite for https://github.com/dtolnay/cxx/issues/876.
=> Partition lifetimes of associated functions

macro/src/expand.rs, syntax/set.rs, syntax/signature.rs, tests/ui/undeclared_lifetime.stderr
Prerequisite for https://github.com/dtolnay/cxx/issues/876.
=> Improve diagnostic on undeclared lifetimes

macro/src/expand.rs, macro/src/lib.rs, syntax/types.rs
Closes https://github.com/dtolnay/cxx/issues/876.
=> Group associated functions by self type
